coreos/mantle

platform/local/cluster.go, platform/local/nsdialer.go, platform/local/nsenter.go
Creating and switching namespaces, which are local to the OS thread, is
rather awkward in Go. Implement the goo once and fix a file descriptor
leak in the process, previously origns was never being closed.
=> platform/local: consolidate namespace entering code

platform/local/dnsmasq.go
mantle doesn't actually provide a ntp server but this is still useful
for checking whether the DHCP options are getting plumbed through
systemd-networkd to systemd-timesyncd.
=> dnsmasq: advertise NTP via DHCP

cmd/kola/etcd.go, cmd/kola/etcdtests/etcdDiscovery.go, cmd/kola/etcdtests/registry.go, platform/local/cluster.go
Add multiple discovery tests for different etcd versions and configurations. Requires image build with both versions: export ETCD_PROTOCOLS="1 2"
/cc @marineam
=> cmd/kola: add multiple etcd discovery tests and better vm cleanup

cmd/kola/etcdtests/etcdDiscovery.go
Logs from a single node aren't enough to identify why intermittent
failures are happening in the cluster as a whole.
=> kola: output logs from all etcd nodes

doc/kola/design.md
We are no longer doing the etcd2 migration, remove it from the roadmap.
=> kola: remove migration from roadmap

Godeps/Godeps.json, Godeps/_workspace/src/github.com/coreos/coreos-cloudinit/config/config.go, Godeps/_workspace/src/github.com/coreos/coreos-cloudinit/config/config_test.go, Godeps/_workspace/src/github.com/coreos/coreos-cloudinit/config/etcd.go, Godeps/_workspace/src/github.com/coreos/coreos-cloudinit/config/etcd2.go, Godeps/_workspace/src/github.com/coreos/coreos-cloudinit/config/user.go, Godeps/_workspace/src/github.com/coreos/coreos-cloudinit/config/validate/rules.go, Godeps/_workspace/src/github.com/coreos/coreos-cloudinit/config/validate/rules_test.go, cmd/kola/etcd.go, cmd/kola/etcdtests/etcdDiscovery.go, cmd/kola/etcdtests/registry.go, cmd/kola/kola.go, platform/gce.go
Kola now has a platform flag that the etcd2 tests are aware of.
`sudo kola etcd`
and
`kola etcd -platform=gce -gce.image=pb-amd64-usr-653-0-0-2015-04-15-1702`
Will successfully run etcd (1 and 2) discovery on qemu and gce.
=> Full gce support for kola

cmd/kola/bootchart.go, cmd/kola/etcd.go, cmd/kola/kola.go, cmd/kola/nfs.go, cmd/kola/qemu.go, platform/gce.go, platform/qemu.go
Global flags in platform were polluting the help options in plume since plume sets its own flags in subcommands. To fix this for now, the global flags go into the main kola package itself. The platform package gets access to the flags from an options struct already used by plume. 
Kola tests nfs and bootchart are also platform aware and run on both without issue.
=> flag cleanup

cmd/kolet/kolet.go, kola/etcdregistry.go, kola/harness.go, kola/miscregistry.go, kola/tests/etcd/discovery.go, kola/tests/misc/nfs.go, platform/platform.go
Kolet binaries are dropped onto newly created machines by the test harness and allow for running native helper or test functions within a test.
Tests can now define native functions it would like to have available. These tests can be run through the ugly closure passed along with the cluster. This closure is used over a struct + method to prevent an import cycle.
This functionality is useful in porting coretest into kola in future PRs.
Right now kolalet binaries are just expected to be in the working dir from which kola is run. Once kolet is in overlay kolet binaries will be in a standard location.
=> kolet: add support for native code in kola tests

kola/harness.go, kola/tests/coretest/fleet.go, kola/tests/coretest/testgroupglue.go, kola/tests/etcd/discovery.go, kola/tests/misc/nfs.go, platform/local/dnsmasq.go, util/logio.go
Lots of individual tests make excessive noise but in many cases we now have sane default output!
```
2015/06/2 16:43:00 kola: === RUN NFS on qemu
2015/06/2 16:43:11 kola: --- PASS: NFS on qemu (10.603s)
2015/06/2 16:43:11 kola: === RUN coretestsLocal on qemu
2015/06/2 16:43:17 kola/tests/coretest: running ServicesActive...
2015/06/2 16:43:17 kola/tests/coretest: running ReadOnly...
2015/06/2 16:43:17 kola/tests/coretest: running CloudConfig...
2015/06/2 16:43:17 kola/tests/coretest: running Script...
2015/06/2 16:43:17 kola/tests/coretest: running PortSSH...
2015/06/2 16:43:17 kola/tests/coretest: running DbusPerms...
2015/06/2 16:43:17 kola/tests/coretest: running Symlink...
2015/06/2 16:43:17 kola/tests/coretest: running UpdateEngineKeys...
2015/06/2 16:43:17 kola: --- PASS: …
```
=> Logging cleanup

cmd/plume/gcecreate.go, cmd/plume/gceupload.go
Added `force` and `set-retries` flag to both commands. Without `--force` the commands will return success but skip any uploading for files that already exist.
The one piece left of these commands that may not be suitable for scripting is the authentication. Its still interactive when you have a token that doesn't work.
=> added gce-upload and gce-create from ore's upload cmd

cmd/kola/kola.go, kola/etcdregistry.go, kola/harness.go, kola/options/options.go, kola/tests/etcd/discovery.go, kola/tests/etcd/rolling.go, kola/tests/etcd/util.go, platform/platform.go
/cc @marineam @yichengq 
The test works by starting a 2.0.12 etcd cluster. Then a rolling upgrade is started by bringing down and replacing the binary of one node at a time. During this , random writes are being made and checked to try and ensure the cluster remains available the entire time. The specific versions are configurable, but right now it tests 2.0.12 -> 2.1.0-alpha.1 using precompiled binaries. As far as this test can tell, the reliable works and the final cluster version is updated.
@marineam I added a bit of a hack to get some flags into the rolling upgrade test itself.
=> add rolling upgrade test to kola

platform/local/dnsmasq.go
```
$ sudo kola qemu
Cluster failed: Network setup failed: LinkAdd() failed: operation not supported
```
Apparently, I didn't build my kernel with CONFIG_BRIDGE.
=> dnsmasq: add more detail in error messages

Godeps/Godeps.json, Godeps/_workspace/src/github.com/coreos/go-systemd/journal/send.go, Godeps/_workspace/src/github.com/coreos/pkg/capnslog/example/hello_dolly.go, Godeps/_workspace/src/github.com/coreos/pkg/capnslog/formatters.go, Godeps/_workspace/src/github.com/coreos/pkg/capnslog/glog_formatter.go, Godeps/_workspace/src/github.com/coreos/pkg/capnslog/init.go, Godeps/_workspace/src/github.com/coreos/pkg/capnslog/init_windows.go, Godeps/_workspace/src/github.com/coreos/pkg/capnslog/journald_formatter.go, Godeps/_workspace/src/github.com/coreos/pkg/capnslog/logmap.go, Godeps/_workspace/src/github.com/coreos/pkg/capnslog/pkg_logger.go, Godeps/_workspace/src/github.com/coreos/pkg/capnslog/syslog_formatter.go, network/omaha/package.go, network/omaha/package_test.go, network/omaha/protocol.go, network/omaha/protocol_test.go, sdk/repo.go
- capnslog has seen a number of updates, and now always has logging enabled by default.
- add support for computing hashes for omaha packages
- a few functions for navigating the SDK
=> Misc updates for manatle's omaha

platform/qemu.go
gets rid of an annoying message:
WARNING: Image format was not specified for '/dev/fdset/1' and probing guessed raw.
Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
Specify the 'raw' format explicitly to remove the restrictions.
=> platform: set format=raw for disk fds passed to qemu

platform/local/etcd.go
etcd needs the member to be in InitialPeerURLsMap.
=> platform/local: fix etcd server configuration

kola/tests/coretest/etcd.go
fixes:
2015-09-01T21:57:23Z kola/tests/coretest: running EtcdUpdateValue...
2015-09-01T21:57:26Z kola: --- FAIL: coretestsCluster on aws (286.267s)
2015-09-01T21:57:26Z kola:         kolet: on native test EtcdUpdateValue: status unhealthy or incomplete: stdout: %!s(<nil>)
stderr: member 50b86a96d459d7ba is healthy: got healthy result from http://172.31.0.225:2379
member 863ba4b74514ea78 is healthy: got healthy result from http://172.31.5.24:2379
member f0b790eb87110478 is healthy: got healthy result from http://172.31.6.199:2379
cluster is healthy
=> kola/tests/coretest: etcd cluster-health now writes to stderr

kola/tests/coretest/core.go
the golang package for fedora does not link to libc, so when kolet is
compiled on fedora, user.Lookup tests will fail at runtime.
=> kola/tests/coretest: run id instead of calling user.Lookup to verify useradd

kola/tests/coretest/etcd.go, kola/tests/etcd/util.go
etcdctl output format has changed recently to include two instances of 'healthy' per member.
etcd also takes a bit more time to come up on aws, so raise the retry count and sleep interval.
=> adjust etcd health checks

platform/util.go
this is useful when debugging the machines spawned by tests.
=> platform: add Manhole

kola/coretest.go
=> kola: re-enable fleet tests ported from coretest

kola/tests/misc/nfs.go
this will hopefully make the nfs tests pass on aws, where the security group disallows nfs connections to the public ip.
=> kola/tests/misc: use private ip in nfs tests

cmd/cork/downloadimage.go, sdk/download.go
Adds a download image command to cork. This is intended to replace curling the image down each time kola runs. Now the image is verified and only updated if its different form the local copy.
=> Downloadimage

build, cmd/cork/build.go, network/omaha/update.go, network/omaha/update_test.go, sdk/omaha/generate.go
This will be useful in the future for a dev server replacement and automated update testing.
=> Add support for generating update payloads

kola/harness.go
previously test names were being printed before being submitted into the
runner's queue, so you would observe a test name being printed much
before it actually began executing, leading to confusion or ordering and
parallelism.
=> kola: print test name when it is actually run

cmd/kola/bootchart.go, cmd/kola/qemu.go, kola/tests/coretest/testgroupglue.go, kola/tests/etcd/discovery.go, kola/tests/etcd/rolling.go, kola/tests/etcd/util.go, kola/tests/fleet/fleet.go, platform/aws.go, platform/gce.go, platform/platform.go, platform/qemu.go, platform/util.go
sort of a heavy-handed approach, but now we establish a new ssh connection for each command executed. this makes it possible to deal with reboots during a test.
added a bit of documentation to Machine and Cluster, and deduplicated the common machine sanity check code.
removed NewCommand from Cluster. not really needed.
=> refactor ssh

cli/cli.go, cmd/cork/create.go, platform/aws.go, platform/local/cluster.go, platform/local/dnsmasq.go, platform/local/nsexec.go, platform/qemu.go, sdk/create.go, sdk/enter.go, system/exec/exec.go, system/exec/exec_test.go, system/exec/multicall.go, system/exec/multicall_test.go
The create and enter commands should be fully functional now. The main issue I can think of that may be an issue for developers is the initial repo sync doesn't support passing an ssh agent into the chroot so git ssh urls cannot be used but the user could re-run repo init after the initial sync to switch. That shouldn't be a problem for automated builds though.
=> cork: create and enter SDK

platform/conf_test.go, platform/util.go
```
mischief@delta ~/code/go/src/github.com/coreos/mantle $ go vet ./...
platform/util.go:67: result of fmt.Errorf call not used
platform/conf_test.go:47: unrecognized printf verb 'i'
platform/conf_test.go:56: unrecognized printf verb 'i'
exit status 1
```
=> platform: fix go vet complaints

cmd/kola/etcdupgrade.go, kola/coretest.go, kola/etcdregistry.go, kola/flannelregistry.go, kola/harness.go, kola/ignitionregistry.go
it no longer makes sense to call this CloudConfig now that we support ignition.
=> kola: rename CloudConfig to UserData

build
I'd like to be able to build from one directory lower by running `../build`.
=> build: clean up build script

util/logio.go, util/retry.go
the following complaints were fixed:
util/logio.go:29:1: exported function LogFrom should have comment or be unexported
util/logio.go:39:1: exported function CopyProgress should have comment or be unexported
util/retry.go:21:1: exported function Retry should have comment or be unexported
=> util: fix golint complaints

version/version.go
the following complaints were fixed:
version/version.go:3:7: exported const Version should have comment or be unexported
=> version: fix golint complaints

sdk/create.go
If sudo or tar fails the bunzip process will happily hang there waiting
for something to read its output. On the flip side if bunzip aborts
early tar itself should also fail and complain about bad input. So this
ordering should be reliable.
=> sdk: reverse wait order of bz2 and tar

sdk/create.go
The build scripts check this file to determine if they are inside the
chroot or not, optionally entering the chroot if needed. The optional
entering part uses cros_sdk but the inside chroot check needs to work.
=> sdk: create debian_chroot flag file

kola/harness.go, kola/register/register.go
Ignoring all the golint stuff for anything under kola/tests for now. Mostly just fixing up comments. The Result struct I un-exported rather then add a comment. Used gorename for safe renaming. 
```
harness.go:46:2: exported var QEMUOptions should have comment or be unexported
harness.go:55:1: comment on exported function RegisterTestOption should be of the form "RegisterTestOption ..."
harness.go:71:6: exported type Result should have comment or be unexported
harness.go:123:1: comment on exported function RunTests should be of the form "RunTests ..."
harness.go:183:1: comment on exported function RunTest should be of the form "RunTest ..."
register/register.go:19:6: exported type Test should have comment or be unexported
register/register.go:31:1: comment on exported function Register …
```
=> kola: improved comments via golint suggestions

kola/tests/ignition/root.go
"-L ROOT" must be supplied in two separate arguments, mkfs.xfs
erroneously accepts this form but will result in the label " ROOT"
in my tests.
=> kola/tests/ignition: fix xfsroot mkfs options

cmd/cork/create.go, sdk/enter.go
This PR adds support for private repositories in the manifest repo, and reduces the prompting done by repo init. 
When an ssh-agent is being used we mount the directory holding the ssh-agent socket in the chroot and copy ~/.ssh/config and ~/.ssh/known_hosts. 
Also ~/.gitconfig is copied into the chroot to avoid repo init prompts and support automated build environments.
Lastly, I added support for specifying a manifest branch to "cork create".
=> Private repo support

sdk/create.go, sdk/download.go
bootstrap_sdk expects .cache/sdks not .cache/sdk.
=> change the cached sdk directory

cmd/cork/create.go, cmd/ore/upload.go, sdk/create.go, sdk/download.go, sdk/omaha/generate.go, sdk/version.go
cork create --sdk-version is now optional. If not specified we will read COREOS_SDK_VERSION from version.txt in the manifest repo. 
I'm shelling out to "git clone" instead of using the git golang lib, hope thats OK.
=> Make cork's --sdk-version optional

sdk/create.go
this is needed if the core user already exists, which is the case on
CoreOS.
=> sdk: only add core user if it does not exist

sdk/enter.go, system/mount.go, system/mount_test.go
The mix of MS_* flags and extra string options makes the plain mount(2)
system call kinda ugly. To clean up code a bit this interface behaves
more like the mount(8) command instead, accepting flags as strings too.
=> system: add a friendlier mount API

cmd/cork/build.go, cmd/kola/kola.go, cmd/kola/updatepayload.go, kola/tests/misc/omaha.go, network/omaha/handler.go, network/omaha/server.go, network/omaha/server_test.go, platform/local/cluster.go, platform/util.go, sdk/const.go, sdk/omaha/generate.go
a successful run looks like so:
```
./build kola && sudo ./bin/kola -v updatepayload
Building kola...
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/go-link-H7Vk2r/go.o: warning: relocation in readonly section `.gopclntab'.
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/../../../../x86_64-pc-linux-gnu/bin/ld: warning: creating a DT_TEXTREL in object.
2016-01-11T23:27:28Z cli: Started logging at level INFO
2016-01-11T23:27:28Z kola: Generating update payload
2016-01-11T23:27:28Z kola: Bringing up test harness cluster
2016-01-11T23:27:28Z etcdserver: name = simple
2016-01-11T23:27:28Z etcdserver: data dir = /tmp/simple-etcd-410624296
2016-01-11T23:27:28Z etcdserver: member dir = /tmp/simple-etcd-410624296/member
2016-01-11T23:27:28Z etcdserver: heartbeat = …
```
=> initial implementation of a stand-alone omaha server and delta_generator/update_engine test

cmd/cork/create.go, sdk/enter.go, sdk/repo.go, sdk/version.go
This now works:
```
cork create --manifest-name release.xml --manifest-branch refs/tags/v962.0.0
```
Note: although git and cork will handle just the tag name like v962.0.0 the current repo will not and sticks a refs/heads prefix on anything that it feels like. cork could use `git ls-remote` to resolve names given to repo but that a difference in behavior between cork and repo itself may be confusing.
=> cork: cleanups and fix cloning tags

kola/tests/misc/selinux.go
current output is:
```
$ sudo ./bin/kola --qemu-image /home/mischief/src/coreos/src/build/images/amd64-usr/latest/coreos_production_image.bin run coreos.selinux.enforce
2016-02-19T00:16:24Z kola: === RUN coreos.selinux.enforce on qemu
2016-02-19T00:16:24Z etcdserver: added local member f3620cbbbe7cd162 [http://localhost:0] to cluster 3bd8c6452814d712
2016-02-19T00:16:25Z etcdserver: set the initial cluster version to 2.2
2016-02-19T00:16:45Z network/ntp: NTP server failed: read udp [::]:123: use of closed network connection
2016-02-19T00:16:45Z kola: --- FAIL: coreos.selinux.enforce on qemu (21.497s)
2016-02-19T00:16:45Z kola:         failed to run "systemctl --no-pager is-active system.slice": output: "unknown" status: "Process exited with: 3. Reason was:  ()"
2016-02-19T00:16:45Z kola: …
```
=> kola/tests/misc: add coreos.selinux.enforce

system/targen/ldd.go, system/targen/ldd_test.go, system/targen/tar.go, system/targen/tar_test.go, test
test output:
```
$ go test -v
=== RUN   TestLdd
--- PASS: TestLdd (0.01s)
ldd_test.go:32: [/lib64/libreadline.so.6 /lib64/libncurses.so.5 /lib64/libc.so.6 /lib64/ld-linux-x86-64.so.2]
=== RUN   TestTarGenBinary
2016-02-26 13:29:36.353377 T | targen: adding binary "/bin/sh"
2016-02-26 13:29:36.353482 T | targen: adding binary "/bin/ls"
2016-02-26 13:29:36.359849 T | targen: copying library "/lib64/libreadline.so.6"
2016-02-26 13:29:36.359871 T | targen: writing file "/lib64/libreadline.so.6"
2016-02-26 13:29:36.360441 T | targen: copying library "/lib64/libncurses.so.5"
2016-02-26 13:29:36.360466 T | targen: writing file "/lib64/libncurses.so.5"
2016-02-26 13:29:36.362728 T | targen: copying library "/lib64/libc.so.6"
2016-02-26 13:29:36.362799 T | targen: writing file "/lib64/libc.so.6" …
```
=> util: add targen, a package that can generate tarballs of binaries

sdk/enter.go
Commit f1c32301 was broken, I apparently renamed a variable during a
rebase and didn't retest it. Good grief.
=> sdk: fix enter

sdk/repo/manifest.go, sdk/repo/manifest_test.go
This piece is a bit verbose, creating data structures for the complete
manifest format (at least approximately the documented manifest format,
differences with the python implementation may exist...). This package's
task is just to test that repo is working properly so it will not
implement the vast majority of its features. Just enough to prase a
manifest and check that the right things are checked out.
Based on docs/manifest-format.txt in repo v1.12.32
=> repo: start basic repo re-implementation in Go

cmd/cork/create.go, sdk/repo/manifest.go, sdk/repo/verify.go, test
Some independent sanity checking to raise my confidence that builds are working.
=> cork: add support for asserting source trees are consistent

kola/harness.go, kola/register/register.go, kola/tests/misc/verity.go
had to move the Skip code to avoid import cycles. sticking it in register seems like a poor choice but it seemed like the best for now.
=> coreos.verity.corruption

kola/tests/kubernetes/smokechecks.go
While we are here, fix kubectl flags to avoid deprecation warnings.
=> kola/tests/kubernetes: bump nginx timeout

lang/destructor/destructor.go, lang/doc.go, platform/local/cluster.go
More specific package names than `util` help keep things organized. This
new package is basically for things Go could have been nice enough to do
for us but doesn't, giving us sads.
First obvious candidate for this is our destructor implementation.
I'll have more stuff for this soon. ;-)
=> lang: create a new package for language utilities

.travis.yml, index/directory.go, index/update.go, index/write.go, index/write_test.go
This is more robust since it can detect deletion of child nodes and
changes to the html template. For now CRC32c is used, if that is
insufficient we can switch to MD5 in the future. As an added bonus,
the storage server validates the upload using the provided hash.
Depends on https://github.com/coreos/mantle/pull/270
Replaces https://github.com/coreos/mantle/pull/265
=> index: use a hash to trigger index updates instead of time

kola/harness.go, kola/register/register.go
This PR adds the ability to specify the minimum semantic version of CoreOS that a given test should run on.
The check is done by spinning up a machine and parsing /etc/os-release before running any tests. This is somewhat costly time-wise. In the future, we may want to simply pass in the CoreOS version by flag. 
To avoid some of the cost, the version check is ignored if the test glob is an exact match. Additionally the second commit adds two fast paths for avoiding spinning up an extra machine.
https://github.com/coreos/mantle/issues/171
=> kola: allow tests to specify min CoreOS semver

cmd/ore/sync.go, lang/worker/group.go, storage/bucket.go, storage/bucket_test.go, storage/error.go, storage/index/indexer.go, storage/index/sync.go, storage/index/tree.go, storage/object.go, storage/object_test.go, storage/ratelimit.go, storage/storage.go, storage/sync.go
This is the core chunk of code for replacing "gsutil rsync && plume index" with a single command that will keeps a local cache of bucket state, avoiding issues caused by the eventual consistency of bucket object listings.
Integrating all this into a new plume command will come in a follow-up commit.
=> New package for managing cloud storage

kola/tests/kubernetes/basic.go, kola/tests/kubernetes/controllerInstall.go, kola/tests/kubernetes/setup.go, kola/tests/kubernetes/workerInstall.go
I removed the testing of the v1.1.7 and v1.1.8 image. I see no reason to keep those around and gate OS releases on them. Also, by updating the setup scripts to v1.2 those images will no longer work so its not worth the maintenance burden.
=> kubernetes v1.2

cover, test
This test script has a lot of suck which is why I didn't tend to use it, but it is nice to have coverage, fmt, and vet all wrapped up into one. Take advantage of `go list` to make `gofmt` work like other commands after which a simple `./...` is all we ever need.
Adds a few other tidbits: go install everything, `go test -i` only installs dependencies, further speeding up incremental builds. Adds a variant of our standard cover script but this one actually accepts target package as an argument like a sane thing should.
Depends on part of https://github.com/coreos/mantle/pull/286 to fix a broken test.
=> test: end the terrible doom of listing packages by hand

lang/maps/sorted.go, lang/maps/sorted_test.go, lang/natsort/cmp.go, lang/natsort/cmp_test.go, lang/natsort/sort.go, lang/natsort/sort_test.go
This is the same sort algorithm as used by Apache httpd's index module with `VersionSort` enabled. Considering that is exactly what all my indexing go is mimicking in the first place that seems fitting. Original version available here: https://github.com/sourcefrog/natsort
Interesting trivia for related software, GNU's `sort --version-sort` implements the full [Debian package version format](https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-Version) which I find quite silly complicated and specific for such a generic thing. ;-)
=> Implement Martin Pool's Natural Order sorting

cmd/plume/plume.go, cmd/plume/release.go, cmd/plume/specs.go, storage/index/job.go
The first commit here is the pretty one, it's the happy layer on top of all the storage infrastructure code I've been working on the past couple weeks. The second one for GCE, not so much. The existing code doesn't quite do all I need it to but today is not the day to invest in it. Cleanups will come later.
This replaces `core_promote` except for updating the roller channel which we have tended to do separately anyway.
=> New plume release command, supporting storage and GCE

kola/tests/systemd/journald.go
v229 appeared in CoreOS 1024+, not 1026.
=> kola: fix coreos version for journald test

storage/bucket.go, storage/index/tree.go
This bug caused http://alpha.release.core-os.net/amd64-usr/ to appear empty.
=> Fix non-recursive index generation

cmd/ore/index.go, cmd/plume/index.go, cmd/plume/release.go, cmd/plume/specs.go, storage/bucket.go
The old `plume index` is now `ore index` and the new command uses the release spec to figure out what storage locations to update rather than needing an explicit list.
=> Replace plume index

cmd/plume/release.go, cmd/plume/specs.go
Name and Description no longer hard-code "coreos" which feels like the
right thing to do but aren't fully templatized because that seems
overkill. Add Family and Licenses attributes, new types of metadata
useful for finding images and tracking usage. Family is not yet passed
to the API because the Google hasn't refreshed their Go API bindings to
include it yet. Will add that once available.
=> plume: define more GCE metedata in release specs

cmd/kola/spawn.go
empty configs are now truely empty, and have no ssh keys injected.
if a config isn't provided, make up a cloud-config so an ssh key gets
injected so that ssh works.
=> cmd/kola: always set a userdata in spawn

kola/harness.go, kola/tests/docker/docker.go
tests a few docker run arguments which influence cgroup settings.
can't test blkio because blkio settings don't work in virtual
environments due to lack of cfq scheduler on virtual controllers.
=> kola/tests/docker: add docker.resources

sdk/enter.go
Something something doomed to [repeat][1] [history][2].
[1]: https://github.com/coreos/scripts/commit/09851b8460010a60168e1803388cca3bc218216c
[2]: https://github.com/coreos/scripts/commit/3fdd2033dc12e5bc10f0690b3755600e4dc47a35
=> sdk: ensure / is a mount point

kola/tests/ignition/v1/empty.go
Reverts coreos/mantle#316
Returning Skip doesn't do anything, the test fails before this function even runs. Nevermind...
=> Revert "kola: disable empty ignition config test"

cmd/ore/create-image.go
I honestly thought this was already here, but I mixed up image creation
with instance creation. Options differ slightly from upload, assembling
the image URL from the board and version instead of taking the full path
and deriving that information from it. In the future I'm going to clean
this up and make usage more consistent across plume, ore, and our build
scripts.
=> ore: add new create-image command

kola/tests/ignition/v2/root.go
Add tests for creating ext4 filesystems in ignition. Test both creating
a new ext4 filesystem in ignition and tests not overwriting an existing
filesystem.
=> kola/tests/ignition: add tests for ext4

kola/tests/systemd/sysusers.go
Here is the output of this new test on an affected version of CoreOS, and a current version.
$ sudo kola --qemu-image ~/trunk/.cache/images/coreos_production_image.bin run systemd.sysusers.gshadow 
2016-06-30T19:09:23Z kola: === RUN systemd.sysusers.gshadow on qemu
2016-06-30T19:09:36Z kola: --- FAIL: systemd.sysusers.gshadow on qemu (12.665s)
2016-06-30T19:09:36Z kola:         failed to run "sudo systemd-sysusers": output: "" status: Process exited with: 139. Reason was:  (SEGV)
2016-06-30T19:09:36Z kola: 0 passed 1 failed 0 skipped out of 1 total
1 tests failed
$ sudo kola run systemd.sysusers.gshadow 
2016-06-30T19:09:50Z kola: === RUN systemd.sysusers.gshadow on qemu
2016-06-30T19:10:00Z kola: --- PASS: systemd.sysusers.gshadow on qemu (9.989s)
2016-06-30T19:10:00Z kola: 1 passed 0 …
=> Add a test for #1394

platform/machine/aws/cluster.go, platform/machine/gcloud/cluster.go, platform/machine/qemu/cluster.go, platform/util.go
Ensure that selinux is enabled when running tests - we want to ensure that
thing we expect to work.
=> platform: Enable selinux when bringing up or rebooting machines

kola/tests/kubernetes/basic.go, kola/tests/kubernetes/controllerInstall.go, kola/tests/kubernetes/setup.go, kola/tests/kubernetes/workerInstall.go
Bumps this test to using our v1.3 coreos-kubernetes scripts found [here](https://github.com/coreos/coreos-kubernetes/tree/master/multi-node/generic) which allows testing of kubernetes with rkt as a runtime.
I generally am OK leaving this test as just testing one version of kubernetes and serving as smoke test for the OS since the scripts in coreos-kubernetes only really support one minor version of kubernetes at a time. 
Tested rkt and docker runtimes on 1122.0.0, tested docker runtime on 1068.9
=> kola/tests/kubernetes: test docker and rkt runtime

kola/tests/rkt/rkt.go
the service name changed from etcd3-wrapper to etcd-wrapper, and we must
specify a tag now.
=> kola/tests/rkt: make etcd-wrapper test work again

kola/tests/ignition/v1/root.go, kola/tests/ignition/v2/root.go
operating on /dev/disk/by-label/ROOT appears to race with udev, at least
when using mkfs.btrfs, so switch to /dev/disk/by-partlabel/ROOT which
appears to not race.
=> kola/tests/ignition: do fs operations on /dev/disk/by-partlabel/ROOT

kola/tests/locksmith/locksmith.go
this exercises locksmithd's locking logic, and will retry if locking
fails. locksmithctl reboot will not retry or block if the lock is
already taken.
=> kola/tests/locksmith: use send-need-reboot instead of reboot

kola/tests/misc/network.go
CoreOS is now shipping systemd-resolved without enabling its DNS stub resolver by default.
=> Remove the systemd-resolved listeners

platform/conf/conf.go
Lets me get away with some shenanigans. When doing this the script must setup ssh keys itself.
=> platform/conf: pass through scripts unmodified

platform/util.go
The return values were swapped so the error check was actually testing
for non-nil stdout. However error messages generally go to stderr so
failures were always ignored. Fix error check and just ignore stdout.
In fixing this I need to still tolerate images that do not have SELinux,
such as ancient versions (for upgrade tests) or non-amd64 ports.
=> platform: fix enabling SELinux

kola/tests/kubernetes/setup.go
I've found this to help with flakes locally. I havn't been able to reproduce any non-timeout related failures with either of these k8s tests.
=> kola/tests/kubernetes: bump timeouts

cmd/kola/spawn.go, kola/harness.go
This change allows for interactive validation of test cloud-configs during development. (For example, test cloud-configs have a $discovery macro that automatically allocates etcd discovery URLs.)
=> kola/spawn: preprocess userdata just like when testing

platform/api/gcloud/compute.go
This tags are needed in addition to the default firewall rules for the
project which in our case already allow it.
=> platform/api/gcloud: allow http and https

kola/tests/misc/files.go
These shouldn't be recursing into the rkt containers.
=> kola/tests: fix suid and sgid tests

kola/tests/rkt/rkt.go
This variable name changed with the new implementation of the wrapper
script. We aren't worrying about backward compatibility here because the
existance of this script was never advertised.
=> kola/tests: update etcd wrapper test

cmd/kola/kola.go, kola/harness.go, kola/registry/registry.go
I have a project vendoring mantle to maintain a separate test suite from the OS test suite. In this scenario I have no control over whether the OS test suite is registered if I wish to use the kola harness from my main package. I could just edit the kola code but I'd like to strictly maintain it as vendored upstream library so all changes to kola go back to this repo.
Moving the registration list to a separate package explicity imported by the main package allows the projects vendoring this code to choose not to register the OS test suite.
Alternatively this list of imports could all just go in the main package instead of having this indirect registry package. I have no opinion on which I like more.
cc @mischief  @crawford
=> make importing OS tests optional from using harness

platform/api/gcloud/compute.go
Somewhere in the shuffle this option stopped being respected. This means its difficult to tell from which CI job rogue kola instances are from and know which ones are safe to reap. Useful now that kola tests are being run in more places also won't harm anything not utilizing the basename option.
cc @marineam
=> platform/api/gcloud: respect basename option

kola/tests/misc/files.go
The tests are checking if files exist with problematic modes, so we
don't care about them if they are deleted before stat is called.
=> kola/tests: fix a bunch of race conditions in files tests

cmd/kola/options.go, platform/api/gcloud/api.go, platform/api/gcloud/compute.go
The gcloud should distinguish the image project from the instance project. Mainly, its useful to be able to select vm images from a project like coreos-cloud but have the instances still spawned on the coreos-gce-testing project. Otherwise one has to guess which jenkin's created image is good. 
cc @marineam @mischief
=> allow selection of image project for gce

Jenkinsfile
Since mantle is a relatively stand-alone project compared to the other OS build jobs, it probably makes more sense to give it a `Jenkinsfile` instead of having a Groovy script for it in coreos/jenkins-os.
=> Jenkinsfile: include the Jenkins pipeline job

kola/tests/coretest/core.go, kola/tests/docker/docker.go, kola/tests/etcd/discovery.go, kola/tests/flannel/flannel.go, kola/tests/fleet/fleet.go, kola/tests/locksmith/locksmith.go, platform/machine/aws/cluster.go, platform/machine/gcloud/cluster.go, platform/platform.go
For fun, here is a list of some of the race conditions I can recall offhand from running kola on GCE (in addition to the non-race problems).
* All tests assume they can run immediately when SSH connects.  There are no service dependency relations between `sshd` and anything being tested.
* Similarly, the cloud-config service has no dependencies with tested services, so even when SSH would connect and start services itself, the services' configuration files sometimes weren't written yet.
* There were the usual `find` races, where files could sometimes be deleted between `readdir` and `stat`.  (This one was fixed separately in #430.)
* The etcd commands will all happily run and fail before the cluster is healthy.  This includes all services acting as etcd clients.
* The fleet daemon doesn't …
=> Fix kola on GCE ... mostly

network/journal/entry.go, network/journal/entry_test.go, network/journal/export.go, network/journal/export_test.go, network/journal/format.go, network/journal/format_test.go
This implements a parser for the journal export format used by journalctl and various journal remote tools:
https://www.freedesktop.org/wiki/Software/systemd/export/
The reason for implementing this is it will enable a higher level journal slurper to SSH to a remote host multiple times and each time resume reading the log where it left off because it'll have access to the __CURSOR field.
Since the export format is overly verbose for humans I've implemented support for writing logs in a format similar to journalctl's default output.
=> New package for processing journals from remote sources

kola/tests/misc/network.go
I believe this fixes a rare race condition, where the TCP listener check fails because `(agetty` is listening on the SSH port.  When systemd forks a service process, it renames the child as the executable name in parentheses, then closes the fds.  So, in theory, the `lsof` command runs between renaming the child process and closing the fds when it's still got the SSH socket it inherited from PID 1.  (We don't need to care about the time before renaming, since it will still be named `systemd` which is whitelisted.)
=> kola/tests/misc: ignore unfinished systemd child listeners

kola/tests/coretest/core.go, kola/tests/etcd/discovery.go, kola/tests/fleet/fleet.go, kola/tests/locksmith/locksmith.go
Many tests were converted to use ignition for configuration without implementing ignition support in the qemu platform code. Disable for now, I'm in the middle of cleaning up the qemu code and will add ignition support in the process.
=> Disable test using ignition on qemu

.gitignore, cli/cli.go, cmd/ore/azure/azure.go, cmd/ore/ore.go
Per the commit descriptions.
Before this change:
```
$ ./bin/ore --debug version    
mantle/ore version 0.0.0
```
With this change:
```
$ ./bin/ore --debug version
2017-01-25T23:14:14Z cli: Started logging at level DEBUG
mantle/ore version 0.0.0
```
=> Fix the `--debug` flag for the `ore` command

platform/conf/conf.go, platform/machine/qemu/cluster.go
On QEMU systems Ignition configs must be passed via fw_cfg instead of a config drive.
=> qemu: add support for passing Ignition configs

cmd/kola/bootchart.go, cmd/kola/etcdupgrade.go, cmd/kola/kola.go, cmd/kola/options.go, cmd/kola/qemu.go, cmd/kola/spawn.go, cmd/kola/updatepayload.go, kola/harness.go, platform/conf/conf.go, platform/local/cluster.go, platform/machine/qemu/cluster.go
kola will now create a temporary directory `_kola_temp` to dump tests
data to, such as machine configuration, journals, etc. To start off with
only QEMU is implemented and only ignition configurations are written.
For example after `kola run` all ignition configs used can be found at:
_kola_temp/$test_name/$machine_id/ignition.json
=> kola: add support for dumping arbitrary test data

platform/local/configdrive.go, platform/machine/qemu/cluster.go, platform/machine/qemu/machine.go
Now in addition to preserving ignition.json, cloud-configs get saved too.
=> qemu: preserve config drives under _kola_temp output directory

kola/tests/docker/docker.go
This includes turning on selinux, running a userns container, and double
checking uid mapping happened as far as proc can tell.
This misses coverage of `--userns-remap=default` doing its implicit-user-creation stuff, but that feature works on fewer total versions and is far less important (since using userns without it is well documented in multiple places)
=> kola/docker: add userns test

network/journal/format.go, network/journal/format_test.go
There is only one formatter right now but an interface feels more
appropriate for this.
=> journal: convert formatter to an interface

lang/bufpipe/fixed_buffer.go, lang/bufpipe/fixed_buffer_test.go, lang/bufpipe/pipe.go, lang/bufpipe/pipe_test.go, network/bufnet/pipe.go, network/bufnet/pipe_test.go, network/mockssh/mockssh.go, network/mockssh/mockssh_test.go
The interesting piece of code here is a simple ssh server: command execution is performed by a `SessionHandler` function which is given a `Session` struct that is the mirror of the client's session. Each server has only one handler and one client and is terminated when the client is closed.
The rest of this code is copy/pasted from `io`, `net`, and `golang.org/x/net/http2` with minor tweaks to implement a buffered versions of `io.Pipe` and `net.Pipe` because connecting the Go ssh server and client to each other without a buffer just results in a deadlock.
Alternatively instead of copying all of that code, sockets created by `socketpair(2)` could be used to use in-kernel buffering just like TCP does but there is no way to create `net.UnixConn` objects from the unix sockets returned by …
=> Mockssh: A basic ssh server/client for testing

kola/tests/docker/docker.go
This test fairly reliably fails for 1235-8 and has passed 2/2 times for 1235-6.
It takes a little under 2 minutes to run, so not too bad.
cc @dm0-
=> kola/docker: add regression test for 1785

cmd/kola/bootchart.go, cmd/kola/spawn.go, kola/harness.go, platform/base.go, platform/local/cluster.go, platform/machine/aws/cluster.go, platform/machine/gcloud/cluster.go, platform/machine/gcloud/machine.go, platform/machine/qemu/cluster.go
One slight catch about this scheme that I've found: if you are switching between platforms between runs of kola you'll need to manually remove the _kola_temp directory after QEMU runs since they run as root while GCE and others can be run as your normal user.
=> Add support for dumping machine user-data and journal to GCE

platform/api/gcloud/compute.go
I had a buggy cluster that kept running out of disk space so I had bumped this locally. Even with out the pod gc bug, a cluster that is running self-hosted etcd already gets somewhat close to running out of disk space. Lets give ourselves a slightly larger margin.
=> platform/api/gcloud: slight increase default gce node root disk size

kola/tests/misc/files.go
This test made kola fail on GCE due to the rkt agent writing dead links in `/var`.  Expand the test coverage to all files, and add an ignore list.
=> kola/tests/misc: ignore dead links in certain paths

kola/harness.go
Missed this 2f417db9. As in `testing` H.Parallel must be called to
enable parallel execution. Switch from a plain two seconds to a random
delay between zero and two seconds for rate limiting since all Parallel
calls will always unblock at the same time.
=> kola: restore parallel test execution

kola/tests/etcd/discovery.go, kola/tests/etcd/rolling.go, kola/tests/etcd/util.go
This test has been tagged as "Manual" since 2015, effectively meaning it
hasn't been run since then. Additionally the test has been broken since
the conversion to Ignition because etcd.service doesn't contain an
Install section so it is impossible to enable. There isn't much point to
keeping this dead/broken code around so just clean it out.
=> kola/tests/etcd: remove etcd0 discovery test

kola/harness.go, kola/register/register.go
This option prevented running a test unless it was specifically
selected, effectively disabling a test because no one does that.
Drop the option to discourage leaving around dead code.
=> kola: remove Manual test restriction

pluton/cluster.go, pluton/spawn/bootkube.go, pluton/tests/bootkube/destructiontests.go
In the future I'd like to this function to become more robust and based
on how the Cluster was setup and what things are expected to be there.
This just lays the groundwork interfacewise so future tests rely on it.
I also hardcode the timeout value to the highest one in use. I don't
think we need to expose it to test writers.
=> pluton: support NodeCheck becoming more flexible

harness/_example/doc.go, harness/_example/main.go, harness/_example/tests.go
Slowly porting kola to the new harness package is a little tricky so I
wanted a clear/concise example of how harness can be used to illustrate
what I'm trying to do.
=> harness: add an example for how to customize test suites

kola/tests/locksmith/locksmith.go
This drops annoying stderr output.
=> kola/tests/locksmith: use OpenSSL certificate verification status

cmd/kola/options.go, cmd/pluton/options.go
Despite documentation to the contrary the default firmware for PC
virtual machines has been bios-256k.bin since QEMU 2.0. As of 2.8 the
older bios.bin has stopped working properly.
=> qemu: fix default PC BIOS image

cmd/pluton/pluton.go, pluton/cluster.go, pluton/spawn/bootkube.go, pluton/spawn/nodeconfig.go, pluton/tests/bootkube/conformance.go, pluton/tests/bootkube/scale.go, pluton/upstream/conformance.go
This makes pluton running on bootkube PRs less high-touch since we can input the hack/quickstart dir from bootkube along with the container. This PR only enables use of the kubelet service files from that directory for now. If no directory is specified we will use the default ones periodically synced with bootkube. 
Depends on: https://github.com/kubernetes-incubator/bootkube/pull/350 and a few more changes on my part here.
cc @marineam
=> pluton: use bootkube's hackdir for configuration of host

kola/tests/coretest/core.go, kola/tests/etcd/discovery.go, kola/tests/flannel/flannel.go, kola/tests/fleet/fleet.go, kola/tests/locksmith/locksmith.go
Apparently `kvm` is the intended value, and this was written for broken versions of systemd.  See the history of `virt.c`: https://github.com/systemd/systemd/commits/master/src/basic/virt.c
=> kola/tests: exclude coreos-metadata from kvm systems

pluton/tests/bootkube/scale.go
cc @xiang90 @hongchaodeng
We can enable this now because of https://github.com/kubernetes-incubator/bootkube/pull/359
=> pluton/tests/bootkube: self-hosted etcd only scales to master nodes

pluton/spawn/bootkube.go
This was causing my bootkube PR for 1.6 updates to fail. Its unclear why, but removing rkt-fly stopped bootkube from nearly immediately exiting. 
It was one of the last remaining differences between how I setup bootkube and the scripts from the in-repo hack-dir. I added the rkt-fly so I could separate stdout from stdin in rkt, there is probably another way to accomplish this.
=> pluton/spawn: don't use rkt-fly on bootkube start

kola/tests/coretest/core.go, kola/tests/etcd/discovery.go, kola/tests/flannel/flannel.go, kola/tests/fleet/fleet.go, kola/tests/locksmith/locksmith.go
The service conditions were previously based on virt-type values, but since systemd v233, "kvm" is returned where "qemu" used to be.  Excluding based on "ConditionVirtualization=kvm" is not feasible
since "kvm" is the detected virt-type for several platforms that do utilize the metadata service.  Since these platforms all require setting coreos.oem.id on the kernel command-line, and QEMU tests run on the base image without that value set, make the service depend on its existence.
=> kola/tests: make coreos-metadata.service depend on coreos.oem.id

kola/tests/misc/install.go
With systemd v233, the default.target.wants links are not used.  It only affected cloudinit, and it went unnoticed since this specific activation path is not used by any test.  Therefore, add a test to make sure /var/lib/coreos-install/user_data actually takes effect.
This tests for coreos/bugs#1872.
=> kola/tests/misc: test the coreos-install cloud-config path

cmd/pluton/options.go, cmd/pluton/pluton.go, platform/api/gcloud/compute.go, pluton/cluster.go, pluton/harness/options.go, pluton/harness/register.go, pluton/harness/run.go, pluton/spawn/bootkube.go, pluton/test.go, pluton/tests/bootkube/conformance.go, pluton/tests/bootkube/destructiontests.go, pluton/tests/bootkube/registry.go, pluton/tests/bootkube/scale.go, pluton/tests/bootkube/smoketest.go
Ready for review! New harness simplifies things so much for pluton considering that I no longer import anything from `kola/`.
Since we generally only run on GCE for bootkube testing I'm punting on support for other cloud platforms for now. It should take very little modification to pipe through something like all the AWS options and have things work, but, I'm mainly unsure of how I want to deal with the notion of a platform from a `pluton.Test` perspective.
=> pluton: use new harness directly

kola/tests/docker/docker.go
With our current alpha kernel it passes. See
https://github.com/coreos/bugs/issues/1826
=> tests/docker/userns: re-enable for aws

cmd/gangue/gangue.go, sdk/download.go
After building with signed bootstrap packages, some new issues arose because the toolchain packages are downloaded into the same directory as built packages.
- The `sdk.UpdateSignedFile` function leaves detached signatures in place, which may be desired in most cases, but since the scripts upload packages by the directory, they would sign the leftover signatures while uploading them.
- The `sdk.UpdateFile` function doesn't respect `umask` since it creates the file with `ioutil.TempFile`, which uses mode `0600`.  This can cause read failures when `emerge` downloads the binary packages as root, then other parts of the SDK scripts try to read them as an unprivileged user.  The change here just uses `ioutil.TempFile` to generate the file name and lets the download function write the file, but …
=> Make gangue downloads cleaner

cmd/cork/create.go, sdk/repo.go, sdk/version.go
This should verify the manifest tag signature before anything attempts to use the repo's contents.
After a quick look over the source, `repo` doesn't appear to run anything out of the repository in its `init` subcommand, so it should be safe to run `repo init`, `git tag -v`, then `repo sync` since the `repo init` is analogous to `git clone`.
The manifest repo was cloned in another place to read its version numbers, so this PR verifies it there as well before returning the versions.
=> Add an option to cork to verify the manifest tag

kola/tests/locksmith/locksmith.go
There is still a race condition in the locksmith reboot test that is not as common as the last one, but suddenly got more annoying since I made kola failures fail the whole OS build again.  It appears to be an EOF from the Go SSH library's `Wait` function copying output, but since it fails rarely and randomly, this is just a shot in the dark.
=> kola/tests/locksmith: ignore a stray racy reboot error

cmd/cork/downloadimage.go
Ore and plume are gaining the ability to work with this format, so it
makes sense to be able to download it
=> cork: update 'aws' platform in download-image

cmd/kolet/kolet.go, kola/cluster/cluster.go
When kolet was converted to use cobra subcommands in c56732e4 the final
`os.Exit(2)` fallback never served its purpose because `cli.Execute()`
always exits the program. This was made worse by the fact that cobra
does not consider running a command without a `Run` method to be an
error, simply printing the `Short` description and returning. When test
registration was working this wasn't noticed because cobra would raise
an error if you did not provide a valid subcommand. In commit 3a073663
test registration in kolet broke because the import line was not
updated. So for the past few months all kolet based tests merely checked
that kolet could execute and print the `Short` description from the run
command. This was further made impossible to notice because the output
of kolet is never …
=> kolet: fix everything

kola/tests/fleet/fleet.go
There was another race failure that caused one of the recent OS builds to fail.  The journal from this test ends abruptly after `fleetd` says it completed the `StartUnit` task, regardless of if the test fails or not.  There isn't anything in the journal from the `hello.service` unit or any transient unit.
So, rather than just wrap this in a `Retry` function, I'd like to at least try to see if the unit actually failed, or if it is still in some preparatory state (since the fleet `active` value is directly taken from the systemd state).  The `fleetctl start` source looks like it should be blocking until non-`Global` services get an `active` systemd state, but this should hopefully verify that if the failure happens again.
=> kola/tests/fleet: show the unit status in the error

kola/cluster/cluster.go, kola/tests/coretest/testgroupglue.go, kola/tests/docker/docker.go, kola/tests/flannel/flannel.go, kola/tests/misc/network.go, kola/tests/misc/nfs.go
Ensures test logs are included in the orderly test output.
=> Migrate some logging from capnslog to harness.

platform/api/aws/api.go, platform/api/aws/s3.go
The original preflight check was meant to be the 'get my identity' call
that didn't require permissions. It turns out I was thinking about this
sts call, not the somewhat-similar iam call.
=> platform/aws: fix pre-flight check

cmd/kola/spawn.go, kola/harness.go, kola/tests/etcd/discovery.go, kola/tests/flannel/flannel.go, kola/tests/kubernetes/setup.go, kola/tests/locksmith/locksmith.go, platform/platform.go, pluton/spawn/bootkube.go
Remove an underutilized feature of `NewMachines` that allowed each machine to use a different config. Except for a few tests using the optional etcd `--name` argument this just resulted in boilerplate cruft to assemble lists of identical strings.
=> Use identical user data for all machines spawned together

cmd/plume/index.go, cmd/plume/specs.go
Avoid accidentally releasing arm64-usr to stable.
=> cmd/plume: Use separate board list for each channel

pluton/cluster.go, pluton/tests/bootkube/smoketest.go
We are seeing very wide variance in container downloads: bump timeouts in
two places that are affected by this. cc @aaronlevy
=> pluton: bump timeouts

kola/harness.go
Honestly I'm not sure how important this is and would be better
performed as some sort of flush mechanism in the journal recorder but
implementing flush would be a bit complicated so this stays for now.
It was broken by the conversion from returning errors to using
Error/Fatal methods rendering this `err` value always nil.
=> kola: restore pause before cluster tear down

cmd/kola/options.go, platform/machine/aws/cluster.go
And I tossed in an error check that lead to a panic if e.g. an HVM ami was specified but the PV-only t1.micro was defaulted.
=> aws: default to HVM / t2 series

pluton/harness/run.go, pluton/spawn/bootkube.go, pluton/spawn/containercache/sshcache.go, pluton/tests/bootkube/registry.go
cc @aaronlevy @marineam 
This sets up a bastion node per test suite that prefetches a given list of containers and extracts them into archives on disk. Once this is done the tests run in parallel and before setting up bootkube, it pulls the container archives and extracts them into the store.
This actually slows down tests runs a bit for a variety of reasons (extra extraction steps, copying containers around on disk, and all nodes having to pull container archives from one machine), but it does allow us to run 7 tests in parallel again. Regardless, this is about stability and isolating as much of the internet downloads to the beginning of a test. Scp'ing around the files isn't the most efficient, but its relatively simple and should be reliable.
One disadvantage is that we have to …
=> pluton: prefetch and cache containers

pluton/spawn/bootkube.go
In the future, as soon as we start using a bootkube binary directly we
can infer nearly all the containers we need to prefetch by starting our
prefetch post bootkube render and inspecting the manifests.
cc @yifan-gu
=> pluton/spawn: bump static prefetched images for latest bootkube

network/omaha/server.go, network/omaha/server_test.go
ipv6 is all sorts of wonky under 17.04, causing our Jenkins to fail.
=> Fix omaha test to work around docker 17.04 bug

pluton/spawn/bootkube.go
This allows the tests to pass after merging
https://github.com/kubernetes-incubator/bootkube/pull/433.
Since work is in progress to change pluton to use the hack scripts, this
is only a temporary fix, and it's easier than porting over all the TLS
certificate placement changes here too.
=> Add flag to disable etcd TLS for pluton.

pluton/spawn/bootkube.go
During the transition to using the hack/scripts directly I reduced the
bootkube timeout from 12 minutes to 5 by accident. Although bootkube is
normally much faster then 12 minutes (with container prefetching) the
timeout should not be this low.
=> pluton/spawn: bump bootkube timeout

pluton/tests/bootkube/registry.go
cc @hongchaodeng self-hosted etcd reboot and api-server deletion tests weren't actually running correctly because they weren't using self-hosted-etcd. Looks like this must have been messed up in a refactor somewhere.
=> pluton/tests/bootkube: incorrect self-hosted-etcd test options

pluton/spawn/nodeconfig.go
Occasionally when running the conformance test locksmith would fail. This should avoid that possibility all together.
=> pluton/spawn: avoid failed locksmith unit

kola/tests/misc/files.go, kola/tests/misc/verity.go, util/retry.go
Unrelatedly, skip the last sleep in util.Retry().
=> kola: Convert filesystem and verity tests to subtests

pluton/tests/bootkube/checkpointertest.go, pluton/tests/bootkube/registry.go
The test will test that the checkpointer should:
1. Be able to checkpoint itself and other checkpoint parents.
2. Be able to start checkpoints after a reboot when API server is
not reachable.
3. Be able to stop and clean up the checkpoints when the parent is
not scheduled to the node anymore.
4. Be able to stop and clean up all checkpoints if the pod checkpointer
itself is not scheduled to the node anymore.
=> pluton/tests/bootkube: Add checkpointer tests.

pluton/cluster.go, pluton/spawn/bootkube.go
This is kind of ugly but seems to be the smallest way to let us test
non-release hyperkubes in the different repo.
=> Pluton: add special hack for hyperkube-git.

kola/tests/docker/docker.go
This validates filesystem selection, security options, etc.
This is to improve confidence in coreos/coreos-overlay#2562
=>  	kola/tests/docker: add 'docker info' parsing test 

kola/tests/docker/docker.go
This tests that a user who previously copied 'docker.service' in full
will still pass basic docker tests.
This test caught the selinux regression I almost introduced by removing the script for a symlink.
=> kola/tests/docker: test copy of old docker.service

kola/tests/docker/docker.go, kola/tests/fleet/fleet.go, kola/tests/locksmith/locksmith.go, kola/tests/misc/files.go
This also includes fixing some command output being displayed as byte arrays.  (And dropping the absolute path wasn't required; it's just so it's possible to test without wrapper scripts.)
=> Fix up some kola test output

pluton/cluster.go, pluton/spawn/bootkube.go
By getting kubectl from the hyperkube image we can simplify a lot of the crusty version handling we had to start hacking around. Should have done this this way from the start. Maybe kubectl used to not be in hyperkube?
cc @diegs
=> pluton: get kubectl from image

cmd/ore/aws/upload.go, cmd/plume/prerelease.go, platform/api/aws/images.go
The old setting was `standard`, which is a legacy type with worse performance (but half the cost). Update for current best practices.  The volume type can still be overridden by the user at launch time.
Unconditionally specify `gp2` in ore.
[Mailing list post](https://groups.google.com/d/msg/coreos-user/3TvZCD6taE4/qbZoMEMHBAAJ)
=> cmd/plume: Specify gp2 EBS volumes on 1451 and up

pluton/spawn/bootkube.go
I know that this might not be used much longer, but it's still worth keeping the versions in sync while we're still using it.
=> Pluton: bump precache image versions.

cmd/kola/options.go, cmd/ore/aws/aws.go, cmd/ore/aws/upload.go
It's too easy to leak instances when we have three different default regions.
=> aws: Default to us-west-2 everywhere, and t2.small

cmd/kola/bootchart.go, cmd/kola/qemu.go, cmd/kola/spawn.go, cmd/kola/updatepayload.go, kola/harness.go, kola/register/register.go, kola/tests/ignition/v2/empty.go, kola/tests/ignition/v2/ssh.go, platform/api/aws/ec2.go, platform/base.go, platform/local/cluster.go, platform/machine/aws/cluster.go, platform/machine/gcloud/cluster.go, platform/machine/qemu/cluster.go, platform/platform.go, pluton/harness/run.go
We were always adding the kola SSH key to both the Ignition config and the platform keystore.  (Exception: `coreos.ignition.*.empty` injects a completely empty config, thus allowing the platform keystore to be handled by coreos-cloudinit.)  Separately test SSH key injection via coreos-metadata and via Ignition.  To support this, add infrastructure for selectively disabling functionality handled by the kola harness or by platform code.
=> kola: Add independent tests of SSH key injection via Ignition and platform

kola/tests/misc/toolbox.go
This is a regression test for the issue where toolbox's fedora updated and
caused breakages.
This is also just a test that the toolbox works at all really.
This doesn't test the root-cause, and a test for that should
be added as well.
=> kola/misc: add toolbox 'dnf install' test

cmd/kola/bootchart.go, cmd/kola/kola.go, cmd/kola/options.go, cmd/kola/qemu.go, cmd/kola/spawn.go, cmd/kola/updatepayload.go, harness/harness.go, harness/suite.go, kola/harness.go
Put test results in a subdirectory of `_kola_temp` named after the platform, date, and pid.  Maintain a `<platform>-latest` symlink in `_kola_temp` that points to that subdirectory.  This prevents simultaneous test runs from clobbering each other and makes it trivial to preserve history across runs.
If `--output-dir` is specified, continue using it directly.
Also save some test run parameters to the output directory and report the directory path to stdout at the end of the run.
=> kola: By default, put test results in a subdirectory of _kola_temp

kola/tests/ignition/root.go
=> kola/tests/ignition: Disable btrfsroot tests on Ignition < 0.16

platform/machine/qemu/disk.go
kpartx in CL 1437.0.0 says:
add map loop0p1 (254:1): 0 262144 linear 7:0 4096
kpartx in Fedora 25 says:
add map loop0p1 (253:4): 0 262144 linear /dev/loop0 4096
=> platform/machine/qemu: Fix MakeDiskTemplate for newer kpartx

cmd/plume/README.md, cmd/plume/index.go, cmd/plume/plume.go, cmd/plume/prerelease.go, cmd/plume/release.go, cmd/plume/specs.go
The dev specs were just copied; maybe they should be define separately and reused in both specs.  Not sure if their values should diverge between automated and user dev builds.
=> Support automating pre-release

platform/machine/qemu/cluster.go
=> platform/machine/qemu: Fix qcow when image path is relative

sdk/create.go, sdk/enter.go, system/exec/multicall.go
Long options were added in sudo 1.8.8. CentOS 7.3 has 1.8.6.
Fixes https://github.com/coreos/mantle/issues/647.
cc: @jedsmith
=> sdk: Use short options for sudo

kola/tests/kubernetes/basic.go, kola/tests/kubernetes/setup.go
This test was inadvertently broken in #633 because it relied on
cloud-config's default behavior of populating `/etc/environment`.
This is the simplest fix for that breakage.
=> tests/kubernetes: fix 'kubernetes.docker' test

cmd/kola/options.go, platform/api/aws/ami.go, platform/api/aws/api.go
This allows a caller to use the channel name instead of the AMI id.
It's meant as a simple quality-of-life improvement.
=> kola/aws: allow specifying a channel for ami id

cmd/plume/prerelease.go
It's convenient to know which image they belong to.
=> cmd/plume: Tag AWS snapshots, not just images

kola/tests/kubernetes/kubelet_wrapper.go
This is a regression test promised in https://github.com/coreos/bugs/issues/2016
This is the stupid-simpleist way of testing that specific regression.
This can be replaced with another test that exercises kubelet-wrapper
additionally, but retains this bindmount, in the future since this test
does run rather slowly for what little work it's doing.
=> tests/kubernetes: add kubelet var-log mount test

kola/tests/rkt/rkt.go
This test is meant to catch a regression in v1492.0.0 whereby `rkt run`
would fail under a systemd unit.
Since Container Linux is the point where a pair of (rkt, systemd) are
run together, and the default rkt `stage1-coreos` interacts with
systemd, it makes sense to test this integration here, not just in rkt's
repo.
The tests introduced here attempt to cover the user-observable details
of the integration between rkt/systemd.
=> kola/tests/rkt: add systemd+rkt integration tests

glide.lock, glide.yaml, platform/conf/conf.go, platform/conf/conf_test.go, vendor/github.com/coreos/ignition/config/config.go
A 2.1.0 struct can contain a 2.0.0 config, but when serialized it contains empty JSON objects that aren't defined in the 2.0.0 spec, causing Ignition to produce warnings. Since Ignition now exports a function for determining the config version, use it to select the correct parser for the config version we have.
=> platform/conf: Use Ignition 2.0.0 parser for 2.0.0 configs

kola/registry/registry.go, kola/tests/torcx/torcx.go
This introduces a new torcx package even though this test could also fit
under the existing docker package. The primary reason is the intent of
this test is for a torcx feature.
It's possible in the long term that this testing should live under the
torcx project itself, but for now I think the testing living in kola is
pragmatic.
This is specifically a regression test for https://github.com/coreos/bugs/issues/2079
=> kola/tests: test enabling a torcx systemd unit

sdk/create.go
Here strings will expand variables when used. This escapes them so they
are expanded when bash is run rather than when cork creates the bashrc
=> cork/create: fix interactive shell check

kola/harness.go, kola/register/register.go, kola/tests/misc/selinux.go, platform/machine/aws/cluster.go, platform/machine/aws/machine.go, platform/machine/esx/cluster.go, platform/machine/esx/machine.go, platform/machine/gcloud/cluster.go, platform/machine/gcloud/machine.go, platform/machine/packet/cluster.go, platform/machine/packet/machine.go, platform/machine/qemu/cluster.go, platform/machine/qemu/machine.go, platform/platform.go, platform/util.go
This PR has two commits:
- The first one adds a new flag to `platform.RuntimeConfig` to signal that selinux should not be enabled when machines are created or rebooted
- The second one modifies the `coreos.selinux.enforce` test to check that selinux is not enabled before enabling it, and then follow [the docs](https://coreos.com/os/docs/latest/selinux.html#enable-selinux-enforcement) to enable selinux, reboot, and check that it is still enabled.
=> selinux: allow disabling and test surviving reboots

cmd/plume/README.md, cmd/plume/prerelease.go, cmd/plume/specs.go
It's slower, but VMDKs have started failing:
plume: unable to create snapshot: could not import snapshot: ClientError:Provided image file was corrupted.
https://github.com/coreos/bugs/issues/2107
=> cmd/plume: Upload raw images to AWS

cmd/ore/aws/upload.go, cmd/plume/prerelease.go, platform/api/aws/images.go
=> platform/api/aws: Drop creation of AMIs with Magnetic storage

kola/tests/docker/docker.go
https://github.com/coreos/coreos-overlay/pull/2703 was merged for 1506 instead of 1520. Update the test to reflect that.
=> kola/tests: change containerd test min version

kola/harness.go, platform/local/dnsmasq.go, platform/machine/qemu/cluster.go, sdk/repo.go
Allows kola to run on arm64 hosts.  Also includes a patch that increases the debug output of dnsmasq.
=> Enable kola on arm64 machines

kola/tests/misc/raid.go
bootengine now handles finding and assembling any raid device that ends
with -hasroot. The rd.auto workaround is no longer necessary.
Depends on https://github.com/coreos/bootengine/pull/130
=> kola/tests: remove root-on-raid workaround

platform/api/esx/api.go, platform/machine/esx/machine.go
Currently we leak a file & folder on the datastore. This adds the
removal of these items to the API and is called inside of `Destroy`
after the serial file is downloaded.
=> platform: add cleanup of serial file and vm folders to esx

cmd/ore/packet/create-device.go, glide.lock, glide.yaml, platform/base.go, platform/conf/conf.go, platform/conf/conf_test.go, platform/local/cluster.go, platform/machine/aws/cluster.go, platform/machine/esx/cluster.go, platform/machine/gcloud/cluster.go, platform/machine/packet/cluster.go, vendor/github.com/coreos/container-linux-config-transpiler/config/config.go, vendor/github.com/coreos/container-linux-config-transpiler/config/platform/platform.go, vendor/github.com/coreos/container-linux-config-transpiler/config/templating/templating.go, vendor/github.com/coreos/container-linux-config-transpiler/config/types/common.go, vendor/github.com/coreos/container-linux-config-transpiler/config/types/passwd.go
This updates the BaseCluster to know what ctplatform it's for, and for
each of those platforms render Container Linux configs appropriately.
Platforms CT does not have specific support for pass in the empty
string, which results in them working fine for any CLCs that do not use
special variables.
These platforms can still use CLCs for userdata as long as they don't
reference special platform-specific variables.
cc @bgilbert
=> platform/base: Render CLCs with platform

kola/tests/docker/docker.go
The previous xargs magic was overly complicated and, more importantly,
resulted in flakes.
This makes it pass more reliably, and still falls in-line with the
regression it was originally written to catch.
=> kola/docker: network more reliably

cmd/kola/spawn.go, platform/machine/qemu/cluster.go
Adds the ability to create a machine with multiple disk drives
attached. Default functionality is unchanged as the original
`NewMachine` function has been renamed to `CreateMachine` which
takes an additional argument of type `QEMUOptions`. A wrapper
function now exists at `NewMachine` which calls `CreateMachine` with
an empty `QEMUOptions` struct.
This only implements a `Disk` option on the `QEMUOptions` struct,
which itself is a struct containing a `Size` string.
Whenever additional disks are present they will have a new `qcow2`
image created for them which is immediately cleaned up similar to
how we are doing for the primary disk currently.
=> platform/machine/qemu/cluster: create machine with multiple devices

kola/tests/kubernetes/basic.go
This test has known issues. Namely, kubernetes 1.3 doesn't work with new
versions of rkt (>1.25) due to re-using volume names.
Upgrading the kubernetes version should fix that specific issue, but is
a more involved process. In the meanwhile, we should disable this since
it's just flaky noise.
=> tests/kubernetes: temporarily disable rkt test

cmd/cork/create.go, sdk/repo.go
This is helpful for, e.g., automated builders which are fine with
discarding git repos.
=> cork: allow repo syncing forcibly

cmd/plume/README.md, cmd/plume/prerelease.go, cmd/plume/specs.go
VMDKs appear to work again.
This reverts commit 28758ce7449b324680095e7605b5fd61973c9d81.
=> Revert "cmd/plume: Upload raw images to AWS"

cmd/plume/specs.go
The channel name is appended to the BaseName, so we were getting `ContainerLinuxUser-user` and `ContainerLinuxDeveloper-developer`.
=> cmd/plume: Change AMI BaseName in user and developer channels

cmd/kola/options.go, kola/harness.go, kola/tests/docker/torcx_manifest_pkgs.go, kola/torcx/torcx_manifest.go
This also adds the ability for kola to take a local copy of a torcx manifest.
cc @lucab
This passed against the current AWS alpha ami after running `./build_torcx_store --upload` and pointing it at the generated torcx manifest (with the scripts changes in https://github.com/coreos/scripts/pull/737)
=> kola/tests/docker: add torcx manifest pkg tests

kola/tests/packages/ipvsadm.go
Make ipvsadm run in numeric mode so its output it the same across all platforms.
=> kola/tests: fix ipvsadm failure on aws

kola/tests/docker/torcx_manifest_pkgs.go
The manifest changes were backported to 1520 to make it to stable.
=> kola/tests/docker: Drop torcx MinVersion to 1520

kola/tests/docker/torcx_manifest_pkgs.go
Docker 17.* attempts to use an existing graphdriver by default, but the test expects its fallback "overlay2" driver.  When a system is booted on 1.12, it will be using "overlay", so the test fails when it reboots into 17.06 and still has "overlay".
This wipes out the /var/lib/docker directory before starting the new version after reboot, so Docker 17.06 will start using the "overlay2" driver.  This effectively changes the test to not be concerned about testing in-place Docker upgrades, rather it is just reusing the same system to test different versions for efficiency.
=> kola/tests/docker: Remove /var/lib/docker before changing versions

kola/tests/misc/raid.go, platform/machine/qemu/cluster.go
The root device is not always vda. Use names that are stable instead.
Unfortunately this trades one race for another until https://github.com/coreos/ignition/pull/446 makes it into a release, since it uses the `/dev/disk/by-path` symlinks which has a race with udev. It might be better to wait until that is merged and Ignition is updated in the overlay before merging this. In my experience testing it, without the Ignition patch it fails ~10% of the time.
Maybe we should disable this test until then?
=> kola/tests: fix race with raid test

platform/api/oci/signer.go, platform/api/oci/signer_test.go
Adds a Signer class which will take a URL and modify the headers
to conform to [draft-cavage-http-signatures-05](https://tools.ietf.org/html/draft-cavage-http-signatures-05#page-3) per the oracleoci spec.
=> platform/api/oci: add oracle oci signer

kola/tests/rkt/rkt.go
We hit a flake due to this on our nightly tests.
rkt does not atomically populate the uuid file, so wait for the uuid to
be written into it as well as the file being created.
=> kola/tests/rkt: wait for uuid file to be non-empty

README.md, cmd/kola/spawn.go
Users seldom want to start a machine and then immediately terminate it.
=> cmd/kola: make -s the default for kola spawn

cmd/kola/spawn.go
Remember to call cluster.Destroy. Running locally this ensures dnsmasq gets killed and doesn't leak processes.
=> kola/spawn: do not leak dnsmasq processes

kola/tests/docker/torcx_docker_flag.go
Support was backported to 1520 (but notably not 1535).
=> kola/tests/docker: reduce docker flag MinVersion to 1520

kola/harness.go
Catch both cases of coreos/bugs#2180, independently of the `extend-filesystems.service` failure.
=> kola: check for additional messages on console

platform/base.go, platform/conf/conf.go
Currently the `IsIgnition` function on the `UserData` object only
returns `true` if the `UserData` is already in `Ignition` form.
CLC's are translated to `Ignition` configs when `Render` is called,
so they should also be marked as `Ignition` in this function.
Renames the function from `IsIgnition` to `IsIgnitionCompatible` to
reflect the change.
More discussion [here](https://github.com/coreos/mantle/pull/730#discussion_r144758775)
=> platform/conf: update userdata isignition to check for clc's

auth/oci.go
When the command-line tool for OCI switched from `bmcs` to `oci` the
default config location moved from `~/.oraclebmc` to `~/.oci`.
=> auth/oci: update config location

kola/tests/docker/torcx_docker_flag.go, platform/api/oci/instance.go, platform/conf/conf.go, platform/machine/oci/cluster.go
Blacklists cloudconfig tests, adds an `IsEmpty` function to `platform/conf`, & implements the `authorized_ssh_key` metadata key.
See individual commit messages for context.
=> platform/oci: update tests

auth/esx.go, auth/oci.go, cmd/kola/options.go
Currently only GCE & Packet have the ability to specify the config
file location. This adds the ability to set it for AWS, ESX & OCI.
=> cmd/kola: add option to specify config file for all platforms

cmd/ore/oci/upload.go, platform/api/oci/image.go
Adds an `upload-image` command for the OCI platform. This only
uploads the image to objectstorage, it does not import the image.
Currently the `go-bmcs-sdk` does not support importing the image
from anything other than a running instance.
Until the support is added you'll need to manually create the image
via the `oci` command-line tool or the web UX.
=> cmd/ore: add upload-image oci command

README.md
Document where mantle reads cloud provider credentials from.
Depends on:
* https://github.com/coreos/mantle/pull/738
=> readme: document where to put credentials

platform/conf/conf.go
It's only used in two user-facing applications, `kola spawn` and `ore packet create-device`. In both cases it would be convenient to accept Container Linux Configs.
=> platform/conf: accept CLCs in conf.Unknown()

kola/tests/etcd/discovery.go, platform/conf/conf.go
I promised a forthcoming test in https://github.com/coreos/coreos-overlay/pull/2720#issuecomment-324794069, so here's a shot at it.
These both pass on images built off master (tested against gce). Neither passes on the current alpha due to them depending on etcdctl v3.
=> kola/etcd: add etcd-member and etcdctl tests

platform/api/aws/ec2.go
This will make cleaning up aws instances reliably easier.
See the individual commits. If desired, I can break out the second one to a separate PR since these are only tangentially related.
=> aws: tag instances on creation, add 'createdby' tag

cmd/ore/aws/gc.go, platform/api/aws/api.go, platform/api/aws/ec2.go
The intent is that running this in a distributed-cron-like-thing should be enough to generally catch leaks.
=> ore: implement 'gc' subcommand for aws

cmd/ore/do/gc.go, cmd/ore/gcloud/gc.go, cmd/ore/oci/gc.go, cmd/ore/packet/gc.go, platform/api/do/api.go, platform/api/gcloud/api.go, platform/api/gcloud/compute.go, platform/api/oci/api.go, platform/api/oci/instance.go, platform/api/packet/api.go
This leaves only `esx` unimplemented.
We currently only GC instances, not images or SSH keys.
=> cmd/ore: Add GC subcommands for do, gcloud, oci, packet

platform/api/do/api.go
This affected image selection when launching images by name, and when deleting them using `ore do delete-image`.
=> platform/api/do: fix GetUserImage returning wrong image

cmd/plume/specs.go
The coreosdev account is defunct. Drop its LaunchPermissions from all channels. Add LaunchPermissions for the prod account on the user channel so we're still testing this functionality in plume.
=> cmd/plume: stop granting AWS launch permissions to coreosdev

kola/harness.go, platform/conf/conf.go
Prevent discovery service problems from causing test failures for tests that don't use it.
=> kola/harness: only obtain discovery URL if needed

harness/harness.go, harness/reporters/json.go, harness/reporters/reporter.go, harness/suite.go, harness/testresult/status.go, kola/harness.go
Adds a new mechanism into the harness to provide support for
additional reporters. New reporters can be defined inside of
`harness/reporters` & should implement the `Reporter` interface.
The first additional reporter provided is the JSONReporter. `kola`
runs will now produce an additional file inside of the `_kola_tmp`
logs named `report.json`.
=> harness: add support for additional reporters

platform/machine/qemu/cluster.go
The serial number is now a parameter of the device.  Fixes run time
warnings like these:
qemu: -drive 'serial' is deprecated, please use the corresponding option of '-device' instead
=> cluster: Fix qemu drive warning

cmd/cork/downloadimage.go
Adds the oci platform to the download-image command of cork.
=> cmd/cork: add oci to download-image

network/journal/record.go, network/journal/record_test.go, platform/journal.go
Save the raw `journalctl -o export` output as well as the output already saved. This enables binary journals to be built using `systemd-journal-remote` and then queried with `journalctl`. If we're concerned about the filesize (expect ~1Mb/machine instance), we could gzip it as well pretty trivially, but since disk is cheap and jenkins ends up xz'ing `_kola_temp` in the end, I'm not too worried.
=> journal: also log raw journal output

kola/harness.go
Detects e.g. failure of iSCSI session recovery when `iscsid` is started on OCI. This is not necessarily an OS problem, but will cause the test to fail anyway.
=> kola: check for disk failure on console

cmd/ore/aws/upload.go
`ore aws upload` is usually used for testing, and PV is not normally required.
=> cmd/ore/aws: don't create PV AMIs by default

kola/tests/locksmith/locksmith.go
[Go 1.9 ignores the certificate subject's CN when any SANs are defined](https://golang.org/doc/go1.9#crypto/x509), so when locksmith is built with 1.9, it requires both the IP address and DNS name as SANs.
This is required for coreos/coreos-overlay#2941.
=> kola/tests/locksmith: Set the DNS name in the X.509 SANs

kola/tests/etcd/discovery.go
The test requires ct rendering which is not available for the OCI
platform.
=> kola/tests: disable coreos.etcd-member.v2-backup-restore on OCI

kola/harness.go, lang/destructor/destructor.go, platform/base.go, platform/journal.go, platform/local/cluster.go, platform/local/dnsmasq.go, platform/local/etcd.go, platform/local/omaha.go, platform/machine/aws/cluster.go, platform/machine/aws/machine.go, platform/machine/do/cluster.go, platform/machine/do/machine.go, platform/machine/esx/machine.go, platform/machine/gcloud/machine.go, platform/machine/oci/machine.go, platform/machine/packet/cluster.go, platform/machine/packet/machine.go, platform/machine/qemu/machine.go, platform/platform.go, update/generator/generator_test.go
Use multierror to keep trying to clean things up when destroying machines, even if part of it errors out. We should clean up as much as possible. Also log the errors in `Destroy()` itself, since the callers rarely look at the return value.
=> Log machine destruction and make Destroy() void

kola/tests/misc/nfs.go
Versions prior to 1618.0.0 have a race between rpcbind and mountd that causes the test to fail. Do not run the test on these version.
=> kola/tests/misc/nfs: require 1618.0.0 or later

kola/harness.go
Make it easier to isolate this error without inspecting the console log.
=> kola: check for bad page table message on console

kola/tests/misc/files.go
Since we previously had users defined in baselayout that were also marked as dynamic users, nss-systemd based its UIDs etc. off those.  When they were deleted from baselayout, more links were created to manage them under `/run/systemd/dynamic-uid`.
This just ignores all of `/run/systemd` in case future changes or different configuration results in more dead links.
=> kola/tests/misc: Ignore dead links in all of /run/systemd

kola/tests/kubernetes/kubelet_wrapper.go
Fix flake due to race preventing the unit name being applied to logs
that we grep through. Additionally update the test to not use deprecated
environment variables and use the current version of kubernetes.
See https://github.com/rkt/rkt/pull/2645 for more details about the
race.
=> kola/test/kubernetes/kubelet_wrapper: fix flake

cmd/kola/options.go
DigitalOcean recently upped the ram in all the droplets for free. Use
beefier instances becuase it costs the same. This should also fix the
coreos.toolbox.dnf-install test that previously failed due to being
OOM-killed
=> kola/options/do: increase default droplet size

kola/harness.go
Skip the test if we can't get an etcd discovery url. If it's an outage
with etcd then we shouldn't fail, if it's a problem with the test suite
we should see a bunch of skips.
Lets have less test flakes.
=> kola/harness: don't fail if its not our fault

platform/machine/do/cluster.go, util/retry.go
Droplet creation frequently fails because DO returns a error 422 and
says try again. Take their advice and try again if droplet creation
fails.
=> platform/machine/do: retry creating droplets

cmd/plume/specs.go, kola/tests/coretest/core.go, kola/tests/etcd/discovery.go, kola/tests/flannel/flannel.go, kola/tests/fleet/fleet.go, kola/tests/kubernetes/setup.go, kola/tests/locksmith/locksmith.go
https://coreos.com/blog/toward-etcd-v3-in-container-linux.html
https://coreos.com/blog/migrating-from-fleet-to-kubernetes.html
=> kola/tests: Drop fleet; switch etcd2 dependencies to etcd-member

kola/tests/misc/update.go
This fixes a race where update-engine sets the boot partition back to USR-A after the test sets it to USR-B.
At least we think that's what going on. This seems to have fixed it locally, but the flakyness of the tests makes it hard to know.
=> kola/tests/misc/update: mask update-engine

cmd/kola/spawn.go, platform/conf/conf.go
To use, run `kola spawn -k`.
Also add `kola spawn {-t,--detach}`, which is sugar for starting a machine, injecting local SSH keys, printing its ID and IP, and exiting.
=> cmd/kola: teach spawn to put local SSH keys into userdata

kola/tests/coretest/core.go
=> kola/tests: add test for MachineID

cmd/ore/packet/create-device.go, cmd/ore/packet/packet.go
To instantiate a Packet API you're required to provide a working
gcloud JSON key & bucket storage URL. To be able to run ore for
Packet on things like Jenkins where we don't have these in the
pre-configured locations we need to add these options and plumb
them through.
=> cmd/ore/packet: add fields required to instantiate API

kola/tests/docker/torcx_manifest_pkgs.go, kola/tests/ignition/resource.go
DigitalOcean doesn't have proper networking in the initramfs. This is a known issue and there's no point cluttering our test logs.
cc @arithx @ajeddeloh
=> kola/tests: disable Ignition remote resource fetches on DO

cmd/kola/options.go
Only the first 100 `t2` instances per region per account per day receive launch CPU credits. Now that AWS has per-second instance billing and we have automatic instance GC, it's safe to switch to a type without this limitation.
=> cmd/kola: switch default AWS instance type to m4.large

cmd/plume/prerelease.go, cmd/plume/release.go, cmd/plume/specs.go, platform/api/aws/images.go
Add `eu-west-3` and `cn-northwest-1`, which don't, to plume.  Add PV AKI ID for `cn-north-1`, which does.
=> Don't create PV AMIs in regions that don't support them

cmd/cork/create.go
Change `cork enter`'s default to be what used to be the --experimental
flag. Rename the flag to --legacy and make that use the old enter
method.
Keep the experimental flag, but make it no-op and warn that it will go
away soon.
Doesn't strictly depend on https://github.com/coreos/mantle/pull/812 but that should probably be merged first.
=> cmd/cork: switch enter default to new enter

sdk/enter.go
This reverts commit 02e1f8c19eb703151086448e5bb8f9ccf91d1cde.
This should finish reverting all of the gpg bind mounting related changes.
=> Revert "cork: pass through gpg sockets"

cmd/kola/spawn.go
When running instances spawned with `kola spawn` alongside instances started in other ways (including `kola spawn -t`), it's easy to accidentally terminate a machine by exiting a shell. To avoid this, when starting a shell which is bound to the lifetime of its instance, add `[bound]` to its shell prompt. Ideally this marker would only appear in the affected shell (and not shells from other SSH connections) but there doesn't seem to be a good way to do that, so it will appear in every shell on that machine.
=> cmd/kola: warn in PS1 if exiting shell will destroy spawned machine

Makefile
A passerby who sees a makefile is likely to type make and expect it to
build the thing, not to redo the vendor folder.
For completeness, I tossed in a test target as well.
I've had this diff locally for a while, and it's saved me from many an accidental re-vendor already.
=> make: default to build

cmd/kola/spawn.go
bash needs to know which characters are non-printing.
=> cmd/kola: fix command line wrapping with [bound] in PS1

platform/api/aws/ec2.go, platform/api/oci/instance.go, platform/api/packet/api.go
Let's have fewer test failures due to clouds being slow.
=> Bump timeouts for packet, ec2

kola/harness.go
The current regex to check for segfaults looks for `SEGV` which
incorrectly triggered when an SSH key on the machine had SEGV in it.
This updates the regex to `SIGSEGV`.
=> kola/harness: update segfault regex

platform/api/aws/images.go
Apparently an AMI's EBS volume might be listed after the ephemeral one.  Don't assume the EBS volume comes first.
Not actually tested.
=> platform/api/aws: look harder for EBS volume in PublishImage

kola/harness.go
Try to detect https://github.com/coreos/bugs/issues/2284.
=> kola: check for GRUB memory corruption on console

platform/api/packet/api.go
Escape `%` characters before embedding `ImageURL` in `coreos-install.service` so systemd doesn't treat them as the start of a unit specifier.
Fixes error on stderr:
kola: creating new machine for semver check: timed out waiting for coreos-install: dial tcp [ip]:9: i/o timeout
and corresponding error in `console.txt`:
systemd[1]: /etc/systemd/system/coreos-install.service:16: Failed to resolve unit specifiers on [url]: Invalid slot
=> platform/api/packet: fix ImageURL containing % characters

kola/tests/locksmith/locksmith.go, kola/tests/misc/update.go, platform/platform.go, platform/util.go
Adds a new utility function `Timeout` and uses it in `coreos.locksmith.cluster` to prevent the test from spinning for extended durations.
=> coreos.locksmith.cluster: switch to using util.Timeout

cmd/cork/create.go, sdk/enter.go, sdk/repo.go
Add cork enter `--legacy` and `--bind-gpg-agent`. Additionally refactor the enter code to make adding new similar options easier and more clear.
The changes in `sdk/repo` are untested at the moment and should be tested with Jenkins before we attempt a release with these changes, although I don't _think_ they should cause any problems.
=> Add cork enter --legacy and --bind-gpg-agent

cmd/kola/options.go, platform/base.go, platform/local/cluster.go, platform/machine/aws/cluster.go, platform/machine/do/cluster.go, platform/machine/esx/cluster.go, platform/machine/gcloud/cluster.go, platform/machine/oci/cluster.go, platform/machine/packet/cluster.go, platform/machine/qemu/cluster.go, platform/platform.go
Add support for enabling debug logging on `systemd-*.unittype` units. It
creates drop in units that sets the environment variable
`SYSTEMD_LOG_LEVEL=debug` for the listed units. It applies to both spawn
and run commands.
I'm not 100% this is the best interface for this. We could make it more generic and let users specify whatever dropins they want, but that makes it more verbose. Hell we could even let them supply a whole Ignition config to append. I think this is a good start though and we can add those things if we decide we want them. I'd like to enable this on the nightly with `systemd-networkd.service` and `systemd-networkd-wait-online.service` to hunt down that flake.
=> kola: add support for debugging systemd units

sdk/enter.go
This is a break is compatibility between the legacy and new sdk enter
methods. Make them both recursive bind mounts.
Wait until after 1772.0.0 is released before merging.
=> sdk/enter: make bind mount recursive.

cmd/kola/options.go, kola/harness.go, kola/registry/registry.go, kola/tests/misc/update.go, kola/tests/misc/verity.go, kola/tests/update/update.go, kola/tests/util/update.go
Creates a new test `coreos.update.updatepayload` that mirrors the
functionality of `kola updatepayload` when an update payload is provided
via the `--update-payload` flag.
=> kola/tests: add updatepayload test

kola/tests/ignition/security.go
Adds a test for custom CA certs via Ignition.
=> kola/tests/ignition: add a security tls test

platform/api/aws/images.go
I'm trying to use `ore` and hit a `SIGSEGV` because we're expecting all
the snapshot import tasks to have a description. Unfortunately, that is
not the case on the account I'm targeting. Since we ourselves always add
a description, we can safely skip those tasks since they can't be one of
ours anyway.
=> platform/aws: check for missing Description before deref

cmd/ore/aws/upload.go
Remember to append the source filename when the bucket prefix is specified. Also drop some dead code and correct some help strings.
=> ore/aws: fix up S3 object name calculation

platform/api/aws/s3.go
Log the full `s3://` path prior to starting the upload for better
feedback. This is symmetrical to the `deleting` message we already log.
Also tweak the log message for when an object exists and force was not
set to make it more obvious what the logic is.
=> platform/aws: tweak logging during during S3 uploads

platform/api/aws/images.go
When creating AMIs, in addition to setting an AMI name, let's also add
an explicit `Name` tag with the same value. This can make it more
convenient to search for AMIs when filtering by multiple tags.
=> platform/aws: add Name tag to created images

platform/journal.go, platform/machine/do/machine.go
DigitalOcean doesn't have a way in the SDK to get the console output so
we're currently returning an empty string. This avoids all console
checks some of which are present in the journal. Changes the function to
return the journal output to enable basic checking.
=> platform/machine/do: return journal output in ConsoleOutput

platform/api/aws/images.go
Include information about the duplicate images when erroring out that
there were multiple images.
=> platform/aws/images: make FindImage more verbose

kola/tests/misc/tls.go
Uses curl and wget commands to query a list of
popular HTTPS URLs, to check that TLS works on
the CL image under test.
closes #571 
**Notes**
- This addition has been tested using AWS, after building the mantle tools on top of changes in #862 (along with the changes in this PR)
- Different URLs may be used - there is no particular reason for including the current URLs in `URLsToFetch`
=> kola/tests: add test to fetch urls using TLS

kola/tests/misc/tls.go
uses process subsitution and grep to filter stderr output,
so only failure messages are logged in stderr
=> kola/tests: tls test - direct wget failure output only to stderr

cmd/ore/aws/upload.go, platform/api/aws/ec2.go
Add tags to snapshots so there is still information about a snapshot
if an ami is deleted but the snapshot is not.
#869 must be merged first
=> ore/aws/upload: add tags to snapshots

kola/tests/misc/aws.go
Test covering friendly names on AWS, recently fixed on some specific instance types at https://github.com/coreos/bugs/issues/2399. This invariant should not be instance-specific though.
=> kola/tests: check for AWS friendly device name

cmd/kola/console.go, harness/harness.go, kola/harness.go
This adds a verbose option and a Long description to check-console.
A message to indicate a cluster is being created to check the semver
is also given during kola run, since this can be a long wait time.
**Notes**
These are some minor edits I made while reading the cmd/kola and /kola code. Overall there is not much I felt needed changing after getting better practice in general with the command line - the main takeaway was learning how the tests are run, how command line options are added, and the policy on logging (with https://github.com/coreos/mantle/pull/861 as a guide).
Enhancements that could be made in future are:
- Running count of the tests remaining (possibly in addition to a progress bar which updates based on a rating we give for how long the test takes to run). The data in …
=> kola: add output messages in run and check-console

cmd/cork/create.go, sdk/enter.go
Change the default behavior or cork enter to use the 8.8.8.8 and 8.8.4.4 nameservers instead of copying the hosts's `/etc/resolv.conf`. Add the `--use-host-dns` flag to allow the old behavior.
Also remove the deprecated `---experimental` flag.
=> Add --use-host-dns flag to cork enter

platform/machine/qemu/cluster.go
qemu-img automatically detects the format of the backing image.
=> platform/machine/qemu/cluster: stop passing backing_fmt to qemu-img

platform/platform.go
Adds an addijtional valid value for the `ID` check of `/etc/os-release`
(`ID="rhcos"`).
=> platform/platform: update check in CheckMachine

platforms.md, runner-readme.md
Adds some markdown files which detail how the kola runner works
internally as well as what constitutes a platform in mantle (and some
common things that need to be implemented).
=> Add kola runner & platforms READMEs

platform/api/aws/api.go, platform/api/aws/ec2.go, platform/api/aws/network.go
Currently kola will only create a SecurityGroup if it is not found. With
this patch it will also create a VPC attached to the SecurityGroup (as
well as the route table, internet gateway, and subnets). This allows
kola to be ran against a fresh account/region and work out of the box.
This patch also adds the ability to detect if searching security groups
by name via filters is disabled and manually filters the list.
=> platform/api/aws/ec2: create networking resources if missing

cmd/kola/kola.go, cmd/kola/options.go, kola/harness.go, kola/register/register.go, platform/base.go, platform/platform.go
Adds `-l`/`--distribution` to `kola` which allows the distribution to be
specified. Two new test flags are also added: `Distros` &
`ExcludeDistros`.
=> *: add distro flag

kola/harness.go, platform/base.go, platform/machine/aws/machine.go, platform/machine/do/machine.go, platform/machine/esx/machine.go, platform/machine/gcloud/machine.go, platform/machine/packet/machine.go, platform/machine/qemu/machine.go, platform/platform.go
Performs the CheckConsole function against journalctl output on all
platforms. This extends the Cluster & Machine interfaces with a new
function JournalOutput.
=> platform: perform CheckConsole against journal on all platforms

kola/tests/systemd/journald.go, kola/tests/systemd/sysusers.go
These tests shouldn't have been enabled on RHCOS initially as the
binaries required for them are not shipped.
=> kola/tests: disable systemd.* tests on RHCOS

kola/tests/coretest/core.go
When the patch initially merged crio wasn't enabled by default, now that
it is switch to checking it over docker.
=> kola/tests: update rhcos.basic to check crio over docker

platform/api/aws/ec2.go, platform/api/aws/iam.go
When running kola on a root account that does not own the S3 objects
that are being fetched for tests the AmazonS3ReadOnlyAccess policy needs
to be added to the role (and the corresponding Instance Profile).
This also adds a conditional retry on machine creation to avoid errors
caused by the eventual consistency nature of AWS in relation to the
Instance Profile creation and subsequent use in machine creation.
=> platform/api/aws: add AmazonS3ReadOnlyAccess to Role

kola/tests/misc/raid.go, platform/machine/qemu/cluster.go
Cleanup qemu disk creation and handling. Unify the additionalDisks and
the primary disk to be the same case. Allow passing arbitary options to
qemu for the disk. Axe a closure that just made things more complicated.
Update the root on raid test to use the new mechanism.
=> platform/qemu: cleanup and extend disk handling

kola/tests/misc/selinux.go
This adapts the existing `coreos.selinux.enforce` test to work on
RHCOS and retain its functionality on CL.
Three other tests have been added to validate changing SELinux
booleans and file contexts, as some additional sanity type tests
around SELinux:
- `coreos.selinux.boolean`
- `coreos.selinux.boolean.persist`
- `coreos.selinux.manage`
Signed-off-by: Micah Abbott <miabbott@redhat.com>
=> kola/tests/misc/selinux:  adapt for RHCOS

platform/api/aws/images.go
Do not merge until after the release is finished, it's having a hard enough time as it is.
Don't create PV ami's in regions that do not support it.
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/virtualization_types.html has the PV supported regions
=> platform/aws/images: drop pv in unsupp. regions

kola/registry/registry.go, kola/tests/crio/crio.go
Add Base (info, reliable network) and Network testing for cri-o for
RHCOS. The tests are based on existing Docker tests, but adapted to
crio pods/containers. The tests are network dependant due to the
need of a kubernetes pause image.
Signed-off-by: Steve Milner <smilner@redhat.com>
Yu Qi Zhang <jerzhang@redhat.com>
=> kola/tests: add basic crio package

glide.lock, glide.yaml
We use glide-vc which does a much better job at cleaning up unused
packages. As far as I can tell the subpackages don't do anything and
just cause confusion and make the glide.yaml file harder to read.
=> glide.*: remove subpackages

kola/tests/crio/crio.go
Fix tests as tty flag needs interactive flag, causing fails.
=> crio: remove tty flag from commands

kola/registry/registry.go, kola/tests/rpmostree/deployments.go, kola/tests/rpmostree/status.go
Adds tests for the following `rpm-ostree` commands:
- status
- upgrade
- rollback
- cleanup
- install
- uninstall
The `install-uninstall` test requires network access to fetch an RPM
from EPEL.
Signed-off-by: Micah Abbott <miabbott@redhat.com>
=> kola/tests: add rpmostree package

kola/registry/registry.go, kola/tests/crio/crio.go, kola/tests/podman/podman.go, kola/tests/util/containers.go
Add base (info, resources, network reliability) and network
connectivity tests between machines for podman.  These tests are based
off the existing docker/crio tests in the repo.
There is an addition workflow test (requires internet) that uses
ngingx to test:
- running/pulling a container with volume mount and port forwarding
- executing commands in an running container
- stopping a container
- removing a container
- deleting a container
=> kola/tests: add podman tests

kola/cluster/cluster.go, kola/harness.go, kola/register/register.go
Adds a new flag (`FailFast`) to test registration, when set to true any
sub-tests will be skipped if a previous sub-test has failed.
=> kola: Add FailFast flag to test registration

kola/tests/ignition/security.go
TLS requests in Ignition require system entropy when none may be
available (coreos/ignition#645 ). This seems to be causing flakes in our
CI on qemu_uefi & packet with this test.
=> kola/tests: disable ignition security.tls test on packet & qemu

kola/tests/rpmostree/deployments.go, kola/tests/rpmostree/status.go, kola/tests/util/rpmostree.go
This started with just moving `GetRpmOstreeStatusJSON` to the `util` package, but grew into re-working the `rpmostree` tests too.
I moved the `rpmostree` tests into their own namespace to be more compliant with the [kola test namespacing policy](https://github.com/coreos/mantle/blob/master/README.md#kola-test-namespacing).
Additionally, I opted to make some of the `rpmostree` tests use the `FailFast` capability.
=> kola/tests: cleanup rpmostree tests + related funcs

kola/tests/rpmostree/status.go
I changed this recently in the RHCOS pipeline, and I think we
want to support people running `kola` against e.g. custom FCOS
builds.
Changing the name really shouldn't break anything.
=> rpmostree: Don't hardcode required osname/stateroot

kola/registry/registry.go, kola/tests/ostree/basic.go, kola/tests/ostree/unlock.go
This adds some simple tests to validate basic `ostree` functionality.  It should cover some of the most common use cases that a FCOS/RHCOS user would encounter.
I used the tests from `atomic-host-tests` as a guide, but did not port the full complement of `ostree` related tests from there.
=> kola/tests: add ostree tests

kola/tests/misc/network.go
Starting with Docker 18.06, the containerd CRI plugin listens on a public port by default.  Enable dockerd so we'll detect this.
=> kola/tests/misc: check for listening ports in the docker stack

cmd/ore/aws/upload.go, cmd/plume/prerelease.go, platform/api/aws/images.go
We want to expand the disk size of Red Hat CoreOS.  Use the JSON
output of `qemu-img info` to get the size of the VMDK, and pass
that on to AWS.
The hardcoded 8GB moves to Plume.  I think to support larger disks
there then we'd need to query the snapshot or so?
=> ore: Introspect disk for size rather than hardcode 8GB

kola/harness.go
Catches https://github.com/coreos/bugs/issues/2526.
=> kola: add check for initrd-cleanup.service SIGTERM on console

cmd/kola/kola.go, platform/machine/qemu/flight.go, util/image.go
Fixes `kola spawn` on RHCOS images without `-b rhcos`, which isn't otherwise necessary.
cc @miabbott
=> platform/qemu: don't try to mangle qcow disk images

kola/tests/ignition/systemd.go
Adds a test that runs on all currently supported distributions that
enables a systemd service that already exists on the machine to test
that systemd-presets is ran.
Fixes #907
=> kola/tests: add Ignition test for enabling systemd service

cmd/plume/specs.go
As of #864, we reject attempts to create a PV AMI in us-east-2, so that region can no longer be the primary region for a partition.  Use us-east-1 instead, which is sufficient for testing purposes.
=> cmd/plume: switch user channel from us-east-2 to us-east-1

cmd/ore/aws/upload.go, cmd/plume/prerelease.go, platform/api/aws/images.go, util/image.go
We were uploading the full disk image (4.5 GiB for CL) but hardcoding an 8 GiB disk size in AMI metadata.  This worked until RHCOS images became larger than 8 GiB.  Continue defaulting `ore aws upload` and plume to an 8 GiB AMI disk, but allow overriding from the ore command line, and add an ore option to autodetect the size from a local image file.
Based on, and obsoletes, https://github.com/coreos/mantle/pull/954.  Tested with a CL image and:
- `ore aws upload`, autodetected file
- `ore aws upload --disk-size-gib`, autodetected file
- `ore aws upload --disk-size-inspect`, autodetected file
- `ore aws upload --disk-size-inspect --file`
- `ore aws upload --disk-size-inspect --source-object` (fails)
- `ore aws upload --disk-size-inspect --source-snapshot` (fails)
- `bin/plume pre-release …
=> ore/aws/upload: --disk-size-gib and --disk-size-inspect, revisited

kola/tests/ignition/resource.go
The original PR was mistakenly merged without a MinVersion in #935.
=> kola/tests/ignition/resource: add MinVersion to versioned s3 test

kola/tests/ignition/resource.go
The test requires networking in the initramfs and as such shouldn't be
ran on these platforms.
=> kola/tests: disable versioned s3 test on qemu & do

platform/api/gcloud/pending.go
Tests have been failing to start lately due to image creation timing out.  It was waiting for five minutes, while it took about six minutes, so double the timeout to ten minutes.
=> platform/api/gcloud: Increase image creation timeout

kola/harness.go, kola/register/register.go, kola/tests/coretest/core.go, kola/tests/crio/crio.go, kola/tests/docker/torcx_manifest_pkgs.go, kola/tests/etcd/discovery.go, kola/tests/etcd/rhcos.go, kola/tests/flannel/flannel.go, kola/tests/ignition/empty.go, kola/tests/ignition/resource.go, kola/tests/kubernetes/kubelet_wrapper.go, kola/tests/locksmith/locksmith.go, kola/tests/misc/tls.go, kola/tests/misc/toolbox.go, kola/tests/ostree/basic.go, kola/tests/ostree/unlock.go, kola/tests/podman/podman.go, kola/tests/rkt/rkt.go, kola/tests/rpmostree/deployments.go, kola/tests/rpmostree/status.go
Tests with this flag set will not be run when running on a platform
that does not provide the networking setup required for Internet.
Currently, the only platform where this is the case is `"qemu"`.
This avoids needing to manually exclude platforms using
`ExcludePlatforms:` for this case.
Fixes: #572 
---
A few notes:
- I looked at the tests that were already excluding `"qemu"`. For the tests that did this, I replaced the `ExcludePlatforms: []string{"qemu"}` with the internet flag, apart from the following:
- coreos.ignition.v2_2.security.tls (kola/tests/ignition/security.go)
- coreos.ignition.v1.ssh.key (kola/tests/ignition/ssh.go)
- coreos.ignition.v2.ssh.key (kola/tests/ignition/ssh.go)
These tests look to exclude QEMU for reasons other than requiring Internet access. (security/TLS …
=> kola: add RequiresInternetAccess register flag

kola/tests/docker/docker.go
Testing some changes results in this test failing for one of the Docker versions when using limits less than 15 megabytes.  No problems were encountered with higher values.
=> kola/tests/docker: Double the memory test limit to 20 megabytes

sdk/enter.go
On Silverblue, `$HOME` is in `/var/home`, so that throws off code that
assumes otherwise. The rest of the SDK assumes `/home` is where the user
home directory will be inside the chroot, so let's keep that assumption
going by building the path to `/home` here too rather than passing
through the original path.
=> sdk/enter: make compatible with Silverblue

kola/tests/rpmostree/status.go
When RHCOS changed the version numbering to something that looks like
`400.7.20190227.0`, it broke the `rpm-ostree status` test.  Example
version output from RHCOS:
`Version: 400.7.20190227.0 (2019-02-27T16:19:34Z)`
This relaxes the regex to match one or more digits, then anything
afterwards, until the first paren is hit.  Since I assume RHCOS and
FCOS are going to use numbers for their versions, this should work for
both situations.
=> kola/tests/rpmostree/status: relax regex matching for version

kola/tests/ignition/passwd.go
The issue found was:
- `got "user1:x:1001:1001::/var/home/user1:/bin/bash"`
- `expected "user1:x:1001:1001::/home/user1:/bin/bash"`
This update updates the expectation for user1 and user2 to
have their homes under `/var/home`.
Note: core still is referenced under `/home`.
=> RHCOS: ignition/password.go: Use proper home paths

kola/tests/ignition/systemd.go, kola/tests/misc/nfs.go
There is a known issue where /var/lib/nfs/etab does not exist
(https://bugzilla.redhat.com/show_bug.cgi?id=1394395). Touching this
file allows nfs-mountd to succeed on RHCOS and doens't break anything on
CL.
=> kola/tests: touch /var/lib/nfs/etab in NFS tests for RHCOS

.travis.yml, Jenkinsfile, update/generator/full_test.go
This picks the general settings that use the latest 1.12 patch version release since we usually forget to follow those.
Also fix the Jenkins build cache and a test's string format so it is able to build.
=> Update CI to Go 1.12

kola/tests/util/containers.go
By default `podman` will reuse layers when building images.  This can
cause problems when building different images using the same
`Dockerfile` as is done in `GenPodmanScratchContainer()`.
=> kola/test/util/containers.go: don't reuse layers when building images

cmd/kola/kola.go, cmd/kola/options.go, kola/tests/ignition/passwd.go, kola/tests/ignition/ssh.go, kola/tests/ostree/basic.go, kola/tests/rpmostree/deployments.go, kola/tests/rpmostree/status.go, platform/cluster.go, platform/conf/conf.go, platform/platform.go
Adds a new flag `--oscontainer` to `kola` which allows the specification
of an oscontainer image pull spec when running against the `rhcos`
distribution. When specified it will create the relevant files & the
systemd units required to perform a `pivot` operation before `sshd`
starts.
Closes #987
=> *: add oscontainer pivot support

.gitignore, kola/harness.go
- Add `_kola_temp` to `.gitignore`
- Bump up warning on no network access from `DEBUG` to `INFO`
The second noted item was something I hit while attempting to recreate some `cri-o` failures. Specifically the tests were not running and under `-v` I could see there was some failure but no information. The `_kola_temp` also was primarily void of data as to why there were "no tests found". It wasn't until I dropped into `-d` that I realized what was happening. However, noting that tests are being skipped feels more like an `INFO` item for users than a development/testing `DEBUG` option.
=> Misc minor items

.gitignore, build, test
Add missing `-mod=vendor` flags to both the `build` & `test` scripts, add `.cache/` to the `.gitignore`, & add a `trap` to remove the `_testbin` folder in `test`.
=> *: minor tweaks

build
Add onto #997 so building native programs works.
=> build: Set -mod=vendor for native builds

README.md, cmd/kola/options.go, cmd/kola/spawn.go, kola/harness.go, kola/register/register.go, kola/tests/docker/docker.go, kola/tests/docker/torcx_docker_flag.go, kola/tests/ignition/resource.go, kola/tests/ignition/systemd.go, kola/tests/misc/cloudinit.go, kola/tests/misc/grub.go, kola/tests/misc/network.go, kola/tests/misc/nfs.go, kola/tests/misc/ntp.go, kola/tests/misc/omaha.go, kola/tests/misc/raid.go, kola/tests/systemd/journald.go, kola/tests/torcx/torcx.go, platform/machine/qemu/cluster.go, platform/machine/qemu/flight.go, platform/machine/unprivqemu/cluster.go, platform/machine/unprivqemu/flight.go, platform/machine/unprivqemu/machine.go, platform/qemu.go, system/exec/exec.go
Adds a new platform `unprivileged-qemu` which is meant to be ran without
root access. It has a restricted set of functionality, such as a lack of
the Local cluster and no networking between machines.
=> *: add unprivileged-qemu platform

cmd/plume/fcos.go, cmd/plume/release.go, cmd/plume/types.go
Per discussions in the [fedora-coreos-tracker](https://github.com/coreos/fedora-coreos-tracker/issues/98#issuecomment-505104633), modify the build metadata structure to better support multi-arch.
=> cmd/plume/fcos: modify build metadata structure

kola/tests/coretest/core.go
I plan to disable it by default, see this commit message:
preset: Don't enable crio.service by default
First, we actually need to reconfigure crio before using
it in primary OpenShift use cases to use the pause image from
the release payload; see
https://github.com/openshift/installer/pull/1761
And also the followup
https://github.com/openshift/installer/pull/1768
Second, having it enabled by default breaks our kola tests
https://github.com/coreos/mantle/issues/1004
because the way it handles networking is broken:
https://github.com/cri-o/cri-o/issues/2478
We don't need to enable it by default; rather, have it
be pulled in by `kubelet.service`.
=> kola: Don't check for crio.service started on RHCOS

platform/cluster.go
Defaults to disabling both fedora-coreos-pinger & Zincati on the FCOS
distribution. Both are using a `90-` config so that it can still be
overridden by individual tests.
Closes #1017
=> platform: disable pinger & zincati by default on FCOS

cmd/plume/release.go, cmd/plume/types.go
Switches the FCOS release-index URLs to use builds.coreos.fedoraproject.org & adds a new `stream` field to the base structure.
=> plume: FCOS URLs & structure update

cmd/ore/aws/upload.go, cmd/plume/prerelease.go, cmd/plume/release.go, platform/api/aws/s3.go
This fixes plume and the underlying library to use "application/json"
as the proper content-type for `releases.json`.
Closes: https://github.com/coreos/mantle/issues/1025
=> plume/s3: use proper content-type for releases.json

platform/api/aws/api.go
A subset of the AWS environment variables are gated behind
SharedConfigState being enabled. This will allow users to specify the
following additional environment variables:
- `AWS_DEFAULT_REGION`
- `AWS_DEFAULT_PROFILE`
- `AWS_SHARED_CREDENTIALS_FILE`
- `AWS_CONFIG_FILE`
Closes #1023
=> platform/api/aws: enable SharedConfigState

kola/tests/crio/crio.go, kola/tests/rpmostree/status.go
- update how version strings are compared in `rpm-ostree` test
- update `crio` tests to start service automatically
- change `crio` tests to use unique pod names
- change `crio` tests to only generate container images if previously not create
=> kola/tests: fixes for RHCOS tests

cmd/plume/release.go, cmd/plume/types.go
Modifies the launch permissions to be public for all AMIs in the
release.json
=> plume: FCOS: modify launch-permissions for AMIs

kola/tests/ignition/systemd.go, kola/tests/misc/tls.go
With this, we get a clean FCOS run on AWS! 🎉
=> kola: skip tests incompatible with FCOS

cmd/ore/aws/upload.go, cmd/plume/prerelease.go, cmd/plume/release.go, platform/api/aws/s3.go
Ideally, we'd be able to signal CloudFront at release time that the
release index has changed. But at least let's upload it with a more
aggressive caching policy so that Cincinnati isn't lagging e.g. a whole
day behind.
See related discussions in:
coreos/fedora-coreos-tracker#232
=> plume: upload release index with max-age=300

kola/tests/packages/python.go
There was a lot of effort put into removing python from  FCOS.
Lets have a simple test that will let us know if python gets
pulled into a build by accident.
=> kola/packages: add no python test for fcos

cmd/plume/prerelease.go, platform/api/aws/images.go
Snapshots are created when copying images to new regions, these extra
resources cost money and should be communicated by the API. Add
additional code in `plume` to throw out said snapshot IDs as they are
not published to end-users.
The end result of this PR from the perspective of command interactions
is that `ore aws copy-image` will have the snapshot ID included in the
JSON output.
=> platform/api/aws/images: return snapshotID from CopyImage 

README.md, cmd/kola/options.go, kola/harness.go
When one or more --blacklist-test provided at run time any test that matches by name or pattern to the provided black list is not added to the list of tests to execute.
Example:
```
$ # Run all linux tests except the nfs ones
$ ./bin/kola --blacklist-test linux.nfs* run linux.*
$ # Run everything but linux.nfs.v3
$ ./bin/kola --blacklist-test linux.nfs.v3 run
```
/cc @miabbott
=> kola: Add --blacklist-test switch

kola/tests/rpmostree/deployments.go, platform/platform.go
The rpm-ostree install/uninstall tests  were failing because bcrypt
is installed in /bin on RHEL CoreOS and /usr/bin in Fedora CoreOS.
=> kola/tests/rpmostree: handle install path for fcos

kola/tests/misc/gce.go
Add a test to ensure the gce agent is running.
=> kola/tests: add test for gce agent

Jenkinsfile, build, cmd/kola/options.go, platform/api/packet/api.go, platform/qemu.go, system/arch.go
This is the starting PR to add possibility to build mantle utilities and run kola on s390x architecture.
The code adds s390x architecture to the list of other supported archs to avoid "not-supported" errors and add functionality to generate qemu command, working for s390x
=> Add s390x support for kola in mantle

test
Prevent unnecessary fetching of vendored libraries
=> test: add mod=vendor to everything in test

platform/qemu.go
In case of x86 architecture fw_cfg is used to pass ignition config file to the KVM guest.
s390x does not support fw_cfg, so guestfs is option to use.
guestfs allows to modify qcow2 image before running it as guest.
Current implementation modifies not the base qcow2 image, but the temporary one, created based on the testing qcow2 image.
Code has implementation of several calls to guestfish utility, it is expected that libguestfs-tools is installed on host.
The according issue is https://github.com/coreos/mantle/issues/1045
The list of commands to execute and their output for s390x case. Filesystems are not hardcoded in the code, but found based on their labels
- guestfish --listen -a $IMG
-- > GUESTFISH_PID=$PID; export GUESTFISH_PID
- guestfish --remote -- run
- guestfish --remote -- …
=> Add guestfs utility usage for s390x, to replace unsupported fw_cfg

platform/qemu.go
Fixed a bug where the `Size` & `ConfPath` (used on `s390x` to inject
Ignition configs)  were reversed when calling `setupDisk` resulting in
errors being spat out by `qemu-img`.
Example error messages:
```
qemu-img: Invalid image size specified! You may use k, M, G, T, P or E suffixes for
qemu-img: kilobytes, megabytes, gigabytes, terabytes, petabytes and exabytes.
```
=> platform/qemu: fix bug in QEMU cluster creation

platform/cluster.go, platform/conf/conf.go, platform/machine/esx/cluster.go
tcsd.service can fail to start on Packet nodes which have TPM due to a
longstanding issue that won't be fixed in the CL lifespan. As such mask
it when running CL on Packet.
Also adds a new `Mask` option to the `AddSystemdUnit` function in
`platform/conf`.
Closes #1056
=> platform/cluster: mask tcsd.service on Packet for CL

cmd/plume/README.md, cmd/plume/fedora.go, cmd/plume/prerelease.go
plume: Adds in useful tags to Fedora Cloud and fixes Fedora Cloud download URL
This PR adds in two new tags to the Fedora Cloud AMI creation steps:
```
"Date":       specTimestamp,
￼"Arch":       specBoard,
```
and it fixes the download URL from https://kojipkgs.fedoraproject.org/compose/cloud/ 
This is the compose I tested my changes on below. https://koji.fedoraproject.org/koji/buildinfo?buildID=1361137
```
[jdoss@sts71 mantle]$ ./bin/plume pre-release --system fedora --channel cloud --version 30 --timestamp 20190820 --respin 0 --board x86_64 --compose-id 1361137 --image-type Cloud-Base --debug
2019-08-20T19:32:14Z cli: Started logging at level DEBUG
2019-08-20T19:32:14Z plume: Running AWS pre-release...
2019-08-20T19:32:14Z plume: Reusing existing image …
```
=> Add in more tags to Fedora Cloud

cmd/plume/prerelease.go
I'm not sure why release and pre-release have two separate option
names for the same thing, which means that the invocation between
release and pre-release differs in a non-intuitive way. This commit
makes them match.
=> plume: rename --system argument to --distro

cmd/plume/README.md, cmd/plume/fedora.go, cmd/plume/release.go
- plume: add release example to the README
- plume: fedora: update s3 bucket names
- plume: release: only try to publish PV AMIs for CL
- plume: release: add code to do fedora release
- plume: fedora: remove templating from spec.AWS.BaseDescription
- plume: fedora: remove short options
- plume: fedora: target prod/dev account based on `--environment`
- plume: remove Prefix from Fedora channelspecs
=> plume: lots of tiny fixups for Fedora distro 

kola/tests/ignition/passwd.go
Now that RHCOS is inheriting some of its config from `fedora-coreos-config`,
it uses the same `base.ign` file that includes a `gecos` entry set to
`CoreOS Admin` for the `core` user.
=> kola/tests/ignition/passwd: update passwd entry for core user on RHCOS

kola/tests/ignition/passwd.go
We fixed RHCOS to use the "canonical" homedir.
=> kola: Change user test for `core` to be /var/home on RHCOS

README.md, cmd/kola/options.go, kola/cluster/cluster.go, platform/cluster.go, platform/platform.go
Adds a new flag that automatically manholes into a machine when a
MustSSH call fails.
=> *: add ssh-on-test-failure flag

kola/tests/podman/podman.go
No reason why not to.
(Actually since mantle is branched we could probably just switch to
assuming tests run on both but eh, later)
=> podman: Also run tests on fcos

kola/tests/podman/podman.go, kola/tests/util/containers.go
First, use `--net=none|host` where applicable unless we actually
*intend* to test networking.  Podman will by default allocate
a bridge even if all you wanted is e.g. some stdout from a container.
Second, only run the network tests on FCOS by default because
right now RHCOS has both `podman` and `cri-o` installed and
this causes networking issues:
https://bugzilla.redhat.com/show_bug.cgi?id=1757572
We do want the "base" podman sanity tests though since
that's how the OpenShift installer works on the bootstrap node.
=> podman: Only run podman network tests on fcos, use --net=none some

kola/harness.go
A minor fix for non x86 platforms to consider qemu-unpriv when getting the architecture in order
to retrieve the correct kolet binary
Closes: #1074
=> Check for qemu-unpriv platform when converting board to arch

cmd/kola/spawn.go
When using `-k` on `kola spawn`, it would seed the userdata with a v2
Ignition config. This of course doesn't work on FCOS. Detect the version
instead and seed according to that.
=> kola/spawn: fix using v2 for FCOS when using -k

platform/machine/unprivqemu/cluster.go, util/common.go
When getting the qemu port, the list of connections in /proc/net/tcp is checked and the localhost address
is compares against. Ensure that the correct value is used for big and little endian arches
Potential fix for: #1068
=> Check endianness when getting the qemu port

cmd/ore/gcloud/create-image.go, cmd/ore/gcloud/upload.go, cmd/plume/release.go, platform/api/gcloud/image.go
For FCOS we support both.  Mainly I'm adding these because
they seem to be prerequisites for accessing the "vTPM" which
is part of the "Shielded Cloud" umbrella.  We want access to the vTPM
to enable support for LUKS bound to vTPM for example.  Also,
for OpenShift, I think at some point we want to enable using TPM
as a "strong identity" for nodes.
=> gcp: Add UEFI_COMPATIBLE and SECURE_BOOT

platform/machine/unprivqemu/cluster.go
Denying external network access indirectly breaks the `podman.go`
tests because podman uses bridging by default, expecting `/etc/resolv.conf`
to exist on the host and dying messily if it isn't.
I don't know of a reason for us to do this by default - probably
what we should do is something like only use `restrict=yes` for
tests that aren't flagged as requiring network.
But for now, let's make unprivqemu work like the other platforms
by default.  (As much as it can; this uses usermode TCP which has
weird limitations like no ICMP, and bugs of course, but it does
mostly work for what we need)
=> platform/unprivqemu: Drop restrict=yes

cmd/kola/spawn.go, kola/tests/misc/raid.go, platform/machine/qemu/cluster.go, platform/machine/unprivqemu/cluster.go, platform/platform.go
As mentioned elsewhere, I'd like to use `kola spawn` in the rpm-ostree CI instead of re-inventing the wheel wrt bringing up temporary VMs, extracting the journal and console, etc... These sets of patches make it more useful for this purpose.
See individual commit messages for details.
=> Some `kola spawn` enhancements

cmd/kola/options.go
Now that CL is branched, let's improve ergonomics here and
default to `fcos` for distro.  This has bit me a few times already
where I ran `kola` directly and forgot the `-b` argument.
=> kola: Change distro default to fcos, drop cl

kola/tests/podman/podman.go
I thought this passed at one time, but it seems to just hang
here.  I tried to debug it a little, but the expected flow here
is opaque to me, and it just doesn't seem worth it.
Bigger picture anyways, rather than inventing our own tests for most
upstream projects, we should run *their* tests that have
already been run in *their* CI too.  This is what I plan to
do for ostree/rpm-ostree at least with FCOS.  Basically download
tests from a container built from upstream sources, pull content
onto host and exec there.
=> kola: Remove podman network-multi test

kola/tests/podman/podman.go
See https://github.com/opencontainers/runc/issues/1980
=> kola/podman: Bump memory tests to 128m for runc

network/ssh.go
I plan to use this for cosa to make it a bit easier to log in
manually to instances created by `cosa kola`.  It will be set
to a predictable path rather than a dir in `/tmp` that one may
have to hunt down.
=> network: Honor MANTLE_SSH_DIR

kola/register/register.go
We just lifted the `restrict=yes` from the qemu-unpriv path
which fixed the podman tests, but didn't remove it from the
`PlatformsNoInternet` list.  This meant that we were still
skipping tests like `crio.base` that now *should* run with
qemu-unpriv.
(In the PR we discussed reworking all of this so that
"no networking" is an opt-in thing for qemu-unpriv,
which I'll do once we've drained the queue of other mantle PRs)
=> kola: Note qemu-unpriv now has networking

kola/tests/crio/crio.go
Adds a test that verifies pods continue when the crio service is restarted.
See: https://access.redhat.com/solutions/3825511
=> kola/tests/crio/crio: Add pods and service restart test

kola/tests/crio/crio.go, kola/tests/etcd/rhcos.go
A few of the tests were relying on the fact that they had flagged
themselves as requiring internet access to prevent being ran on
`qemu-unpriv` (which does not support clusters as machines cannot talk
to each other) that are now failing on the platform.
=> kola/tests: disable additional clustered tests on qemu-unpriv

build, platform/api/packet/api.go, platform/qemu.go, system/arch.go
This allows kola to be build and run on ppc64le, although the tests will not yet pass.
=> kola: initial ppc64le support

kola/tests/ignition/empty.go
`tcsd.service` is still flaking there, because there's no Ignition config to mask the service with.  Exclude the test to avoid the flake.
=> kola/tests: exclude cl.ignition.misc.empty on Packet

cmd/kola/options.go, cmd/ore/packet/create-device.go, platform/api/packet/api.go
Drop bogus `baremetal_3a` plan for s390x.
=> *: drop legacy names for Packet plans

cmd/ore/aliyun/list-regions.go
Add an ore command to list the available regions in aliyun
Somehow missed this commit in #1100
=> cmd/ore/aliyun: add list-regions command

kola/tests/rpmostree/deployments.go
Drop the Architecture from the NVRA in the check as it can only pass on the hard coded A. Is there any reason to have the A checked there? i386(stray multilib package)?
=> kola/tests/rpmostree: use NVR instead of NVRA

auth/aliyun.go
The code is expecting `~/.aliyun/config.json` to be a list of profiles,
but the one I have (that was created by the `aliyun` CLI) is an object
where the `profiles` key is a list of profile objects:
```
{
"current": "default",
"profiles": [
{
"name": "default",
"access_key_id": "...",
"access_key_secret": "...",
"region_id": "...",
...
}
],
"meta_path": ""
}
```
Fix the code to adapt to this.
=> auth/aliyun: fix parsing config file

cmd/ore/aliyun/create-image.go, platform/api/aliyun/api.go
Match what `ore aws upload` does and delete the OSS file by default
after the image was successfully uploaded. Then the GC strategy for
pipelines is just about cleaning up old images, and we don't have to
worry about the bucket too.
Closes: #1106
=> ore/aliyun: add --delete-object and default to true

kola/tests/rpmostree/deployments.go
epel7 is not available for s390x. Thus changing to epel 8 and I picked bird because it was available on all arches and was a small self contained package.
Any other suggestions are welcome.
=> Change kola rpmostree install/unistall test package to epel 8 and bird

kola/tests/coretest/core.go
We shouldn't be writing anything to it, and this regressed
in RHCOS.
See https://bugzilla.redhat.com/show_bug.cgi?id=1762509
=> kola: Add a test that /etc/sysconfig/network-scripts is empty

platform/api/aws/images.go
We should just match whatever permissions are set on the source
snapshot.
Closes: #1111
=> platform/api/aws: copy createVolumePermission when replicating

platform/api/aliyun/api.go, platform/api/aws/images.go
Similarly to the AWS analogue of this command, wait until the import
task is complete before returning. Otherwise, e.g. we'll end up deleting
the OSS object beforehand and the task will naturally fail.
=> platform/api/aliyun: wait until import is complete

cmd/ore/aliyun/aliyun.go
Similar to the `AWS_SHARED_CREDENTIALS_FILE`. This will allow us to
more easily point `ore` to the mounted secret inside the RHCOS pipeline.
=> WIP: cmd/ore/aliyun: support ALIYUN_CONFIG_FILE env var

kola/tests/coretest/core.go
We don't explicitly expect sssd.service to be on as older versions of RHCOS have the service off by default.
See: https://bugzilla.redhat.com/show_bug.cgi?id=1749910
=> kola: Allow sssd.service to be on in RHCOS

cmd/ore/azure/delete-image.go, platform/api/azure/image.go
This PR adds a new subcommand to remove uploaded image on Azure
Fixes #1115
=> azure: support removing images in ore

Makefile
Same rationale as https://github.com/coreos/ignition-dracut/pull/106/commits/9b66bf5cb688217f2e3c6d0f3e92a4fa5c1ea46e
This is a standard rule that one can use when developing on
the software.  Further, with this we can change the cosa `Makefile`
that's currently installing to just invoke this one.
=> build-sys: Add `make install`

build
We're not using this for FCOS, and the cross build for kolet
was slowing down local build iteration times.
=> build-sys: Don't cross-build kolet by default

platform/machine/unprivqemu/cluster.go, platform/machine/unprivqemu/machine.go
The duplication in qemu code between cosa and kola needs
to end - this is the start of moving some bits into kola.
Eventually we'll have `cosa run` be a wrapper for something
like `kola qemuexec`.
This bit is the equivalent of
https://github.com/coreos/coreos-assembler/pull/878/commits/55c9b651e5ee94fb4de947a943df213ff3c601eb
We want to strongly emphasize use of TPM devices in CoreOS, so let's provision
one by default.
They can be used for disk encryption, secure secret storage, etc.
=> kola/qemu: Add a swtpm by default

kola/registry/registry.go, kola/tests/rhcos/luks.go
Depends https://github.com/coreos/mantle/pull/1120
See https://github.com/openshift/enhancements/blob/b5e77b5a99dc19de9acfa27fb0758ca42d74f3ee/enhancements/automated-policy-based-disencryption.md
=>  kola: Add a test for RHCOS with LUKS+TPM encryption

cmd/kola/kola.go, cmd/kola/options.go, platform/machine/qemu/flight.go, platform/machine/unprivqemu/cluster.go, platform/machine/unprivqemu/machine.go
Architectures like s390x and pcc64le do not seem to have support for the virtual
TPM device in qemu. The kola tests fail to run today because it requires TPM support
by default.
With the --qemu-swtpm option specified, kola tests can be run on qemu images without TPM when setting it to false. For the tests that require TPM such as rhcos.luks.tpm, they can be blacklisted in the config. By default TPM is enabled for qemu.
=> Add a --qemu-swtpm option to kola to support running kola tests without TPM

cmd/kola/kola.go, kola/harness.go, kola/register/register.go, kola/tests/rhcos/luks.go
Based on the comments in https://github.com/coreos/coreos-assembler/pull/977#issuecomment-562677361, it makes sense to have an option to hardcode excluding certain tests which might never be supported for certain architectures. One good example is the rhcos.luks.tpm test which will probably never by supported on s390x. For powerpc , there is no concrete plans although there is talk of some effort soon.
=> Add ExcludeArchitectures option for kola tests to exclude tests on certain arches

kola/tests/fips/fips.go
The OpenShift installer generates this, and we regressed on handling it.
=> kola/fips: Add user/group to file

kola/harness.go, platform/machine/qemu/flight.go, platform/machine/unprivqemu/flight.go
Today the unprivqemu code inherits this from qemu; flip
that dependency around as preparation for removal of the qemu
path.
=> qemu: Move Options struct into unprivqemu

kola/harness.go
I had the fips test hang, and this might have helped.  What
I really want to do is change things so we *stream* (or poll)
the console and more quickly detect fatal errors.  But in
the meantime, let's add this error since it's definitely fatal.
=> kola: Also check for fatal dracut errors

kola/tests/coretest/core.go
I want to change kola to run `basic` first; no point in running
tons of tests on a system that doesn't boot.  This is a preparatory
step for that, and also just a general cleanup.
=> kola: Unify fcos/rhcos's `basic` test

kola/tests/ignition/mount.go
Adds tests for mounting additional disks at /var/lib/containers
and /var/log. Instead of mounting new disks, tests add new partitions
under the disk `vda`. Currently, there are four partitions, i.e. vda1
-vda4, so new partitions will start from vda5. Particularly, vda5 ->
/var/lib/containers, and vda6 -> /var/log.
~Before running the test, add 2G more space to the disk `vda` since
`vda5` and `vda6` will each take 1G space. Detailed explanations can
be found at https://gist.github.com/zonggen/d888b1ece140f8592a70137d35050073~
Closes: https://jira.coreos.com/browse/GRPA-1203
Signed-off-by: Allen Bai <abai@redhat.com>
EDIT: barred adding space part
=> ignition/mount.go: add tests for mounting additional disks

kola/tests/coretest/core.go
It doesn't play well with `cosa kola` in OpenShift. We should enable it
only when we're not on qemu-unpriv. We do want the `PodmanEcho` test
though.
=> kola: disable PodmanPing and add PodmanWgetHead in fcos.internet

kola/tests/fips/fips.go
Just to make the Ignition config a bit more realistic. Covers a recent
regression we had in that area:
https://github.com/coreos/mantle/pull/1128#issuecomment-564766733
=> kola/fips: Add a partition to Ignition config

cmd/kolet/kolet.go, kola/harness.go, kola/register/register.go, kola/tests/coretest/core.go, kola/tests/ignition/resource.go, kola/tests/ignition/security.go
Support to exclude/blacklist native tests run by kolet. Following up on #1132, this is a way to exclude a certain native test instead of excluding the whole set of tests
Closes: #1132
=> Support excluding and blacklisting basic tests' subtest per arch

cmd/kola/options.go, platform/machine/qemu/cluster.go, platform/machine/unprivqemu/cluster.go, platform/machine/unprivqemu/flight.go, platform/qemu.go
What we really need here is to port the uefi/uefi-secure stuff
from `cosa run`.  In the meantime this is mostly CL cruft; delete
it in prep for a qemu refactoring.
=> kola: Remove --qemu-bios argument

platform/machine/unprivqemu/cluster.go, platform/machine/unprivqemu/machine.go, platform/qemu.go
In preparation for much more extensive use of qemu options for testing
(e.g. supporting uefi-secure, nmve for disks, etc.) rework the internal
QEMU bits to use a "builder+instance" pattern.
The `CreateQEMUCommand` API was growing a lot of arguments; a builder
struct helps that.
We can now more fully encapsulate qemu implementation details;
for example, `Virtio` is no longer exported.  The higher level
code needs to do much less construction of qemu command lines.
One twist with all of this is handling the Ignition config is
pretty different depending on whether the "board" supports `-fw_cfg`.
I reworked the way we handle disks to more clearly distinguish
the "primary" disk (where we may need to inject Ignition) versus
others.
The `QemuInstance` struct better encapsulates the qemu and …
=> Rework qemu to use a better API

cmd/kola/options.go, platform/machine/unprivqemu/cluster.go, platform/machine/unprivqemu/flight.go, platform/qemu.go
We need to test NVMe, we had a regression here.  See
https://github.com/coreos/coreos-assembler/pull/906/commits/be564b7d79466fafb92e2b9d6657cfa3c6b65fae
Part of draining `cosa run` bits into mantle.
=> kola: Add --qemu-nvme

cmd/kola/kola.go, cmd/kola/options.go, kola/harness.go, platform/platform.go
Today the fcos pipeline uses `kola run || :` and then inspects
the output JSON, but that may mask other errors not from tests.
Add an explicit way to `exit 0` even if tests fail, but we still
exit non-zero if e.g. we can't write to the output directory.
=> kola: Add -T/--no-test-exit-error

cmd/kola/kola.go, cmd/kola/options.go, platform/machine/unprivqemu/cluster.go, platform/machine/unprivqemu/flight.go
In some cases we want to test expanding the disk to a specific
size.  Mainly writing this for `cosa kola spawn -- --qemu-size 32G`
for example.
=> kola: Add --qemu-size

platform/machine/unprivqemu/cluster.go, platform/qemu.go
I think we should have done this instead of
https://github.com/coreos/coreos-assembler/pull/973
This way invoking `kola` rather than `cosa kola` does the right thing.
Part of de-duping cosa and mantle.
=> qemu: Automatically turn off swtpm on !x86_64 here

platform/qemu.go
Notably aarch64 is believed to have it.  We'll find out.
=> kola/qemu: Add supportsSwtpm() and just exclude ppc64le+s390x

platform/machine/unprivqemu/cluster.go, platform/qemu.go
First, actually assign the `inst` struct that we return.  Now,
let's call `Wait()` synchronously to ensure that the processes
are dead.
Prep for further fixes around `--parallel` with qemu.
=> kola/qemu: Fix leaking qemu instances

cmd/ore/aws/copy-image.go, cmd/plume/prerelease.go, platform/api/aws/images.go
Rather than accumulate all the results and then dump it all on stdout,
stream the output as line-separated JSON objects as the goroutines
complete.
This is technically a compatibility break since we change the format of
the output. However, I'm not aware of any clients which use `copy-image`
directly and not through cosa.
Prep for making use of this in cosa to speed up `cosa aws-replicate`.
=> ore/aws/copy-image: stream results back to stdout

platform/qemu.go
This will make failures harder to debug in the future, but
avoids spew on the normal case when qemu gets killed first today.
=> qemu: Silence errors from swtpm by default

kola/tests/crio/crio.go
When testing the change from `crictl` 1.14 to 1.16, it was observed
that the `crio.base` tests were failing.  It looks like the `crictl
create` operation is trying to pull images like `localhost/sleep` from
what it thinks is a proper registry at `http://localhost`.
Using the `--no-pull` option avoids this error and allows the tests to
pass successfully.
Regression in `crictl` reported https://github.com/kubernetes-sigs/cri-tools/issues/548
=> kola/test/crio: don't try to pull local images during crictl create

cmd/kola/options.go, cosa/build.go, platform/platform.go
This starts the ball rolling on having mantle understand cosa,
which is key for long-term dedup of the projects.
The main motivation for this right now is that by decoding the
JSON into a Go struct, we are effectively doing a schema validation.
After this lands I'll make a separate PR to flesh out the struct
entirely, then change the decoder to error on unknown keys.
This also removes some CL cruft around the default disk image.
=> kola: Add a --cosa-build argument

cmd/kola/options.go
The new `cosa-build` parameter checks were erroring when both it and
`qemu-image` were not present even when running on non `qemu` platforms.
=> cmd/kola/options: Fix error when running on non-qemu platforms

cmd/ore/aliyun/aliyun.go, cmd/ore/aliyun/create-image.go, platform/api/aliyun/api.go
Adds the ability for the following functions to re-use existing objects
when force is not specified:
- ImportImage
- UploadFile
=> platform/api/aliyun: add re-use capabilities to some functions

cmd/ore/gcloud/upload.go
coreos-assembler was trying to re-create the URL that ore computed
for the storage, and a recent refactoring broke that.
Add an option to write out the URL we used so we only need
to have its computation in one place.
Specifically, cosa started replacing `.` with `-` but ore wasn't.
xref https://github.com/coreos/coreos-assembler/issues/1078
=> ore/gcloud: Add --write-url argument

kola/tests/upgrade/basic.go
The previous function name (`upgradeFromPrevious`) dates from an earlier
iteration where I had initially a `fcos.upgrade.from-previous` and a
`fcos.upgrade.from-current`. Though I changed it later to just have one
test.  Rename the function to match the final name.
=> tests/upgrade: tweak test function name

platform/qemu.go
A minor bug in the way case statements are written in golang. They either require a fallthrough in each case or all the cases specified in the same case statement. Chose the latter as the list is not too
big
=> Fix case statement in helper functions for fwcfg and swtpm

kola/tests/rpmostree/status.go
Since ostree version strings can be completely arbitrary (even whitespace and emoji!), let's just relax the regex to be more accomodating.
=> kola/tests/rpmostree: relax regex on CoreOS version strings

cmd/kola/qemuexec.go, platform/qemu.go
This runs qemu directly as a subprocess, and supports providing
additional arguments to qemu.
Prep for rebasing `cosa run` on this, and draining more of the
qemu logic into mantle so we can share it between mantle/cosa.
=> qemuexec: New command

kola/tests/coretest/core.go, kola/tests/ignition/execution.go, kola/tests/ignition/mount.go, kola/tests/ignition/passwd.go, kola/tests/ignition/resource.go, kola/tests/ignition/security.go, kola/tests/ignition/sethostname.go, kola/tests/ignition/ssh.go, kola/tests/misc/auth.go, kola/tests/misc/selinux.go, kola/tests/ostree/basic.go, kola/tests/ostree/unlock.go, kola/tests/podman/podman.go, kola/tests/rpmostree/deployments.go, kola/tests/rpmostree/status.go
No reason to specify it now that we dropped CL support, so
remove it from all the tests.
=> kola: Remove Distros{fcos,rhcos} from tests - it's the default

cmd/kola/options.go
We translate this in a few places, but let's have the default
be right.  Hit this while working on a new kola subcommand.
=> kola: Default to qemu-unpriv

kola/tests/rhcos/sssd.go
This test verifies changes made in https://gitlab.cee.redhat.com/coreos/redhat-coreos/commit/03ba15aa429af7bf07531e0a533d691dbfd623c4
does not cause regression by checking `altfiles` is not deleted from /etc/nsswitch.conf,
which is the case when calling `authselect select sssd ...` with the `authselect` that comes with
the image.
In addition, also tests that `pam_sss.so` is present in pam config files, e.g.
/etc/pam.d/password-auth and /etc/pam.d/system-auth.
Signed-off-by: Allen Bai <abai@redhat.com>
=> kola/sssd.go: verifies pam configs correctly configured and no regressions are hit

cmd/kola/kola.go, cmd/kola/options.go
Prep for adding more commands which need `syncOptions`; rather
than having `syncOptions` and `syncCosaOptions`, make the upgrade
test the exception that skips the latter.
=> kola: Rework syncOptions

cmd/kola/options.go, sdk/ignversion.go
And use it if no version is specified, and we're
testing qemu and have a disk image path.
Part of draining bits of cosa into mantle so they can
be reused for more testing.
=> kola: Add helper to guess Ignition version from OS

cmd/kola/kola.go
Adds show filter for `kola list`, usage:
- `kola list --platform qemu --distro rhcos`
- `kola list -p qemu -b rhcos`
Signed-off-by: Allen Bai <abai@redhat.com>
Closes: https://github.com/coreos/mantle/issues/1160
=> kola/list: add show filter for `kola list`

platform/qemu.go
This is used for device enumeration order, and is required for NVMe
drives apparently.  Hit this while trying to use a NVMe device as
a target for coreos-install testing (not primary disk).
=> qemu: Always add serial= for disks

platform/qemu.go
Regression from 73831285bf5f85af95bb202f0349545f45ac278f which
broke `coreos.ignition.mount.disks` because we were overriding
the provided serial.
=> qemu: Only set serial= if not already provided

kola/tests/ignition/mount.go
Changed from by-partlabel to by-partuuid by assigning a random uuid. On s390x, the by-partlabel string is incorrect because GPT partitioning uses little endian by default and s390x is big endian. Refer
to: https://github.com/coreos/ignition-dracut/pull/100#issuecomment-529948403.
=> kola: Use uuid instead of partlabel for ignition.mount disk test

cmd/kola/options.go
Regression from d4b252bb7c8b77e73ad6926de70921e95eeb95e5
We need to keep parsing the cosa build, just not actually use it
to sync the target options in order to match how the upgrade
test works.
=> kola: Fix syncOptions

README.md
Update README for `cl` branch, since that'll become the GitHub default.
=> README: redirect FCOS/RHCOS users to cosa in CL branch
