auth/google.go
cli/cli.go
cli/help.go
cli/version.go
cmd/plume/index.go
cmd/plume/plume.go
index/directory.go
index/update.go
index/write.go
network/retrydialer.go
network/ssh.go
network/ssh_test.go
platform/local/cluster.go
platform/local/configdrive.go
platform/local/dnsmasq.go
platform/local/nsdialer.go
platform/local/tap.go
platform/platform.go
platform/qemu.go
util/tmpfile_linux.go

This switch was recently made to most of our other go projects.

*: change license header to line comments

---

platform/local/cluster.go
platform/local/nsexec.go
platform/platform.go
platform/qemu.go
util/exec.go
util/exec_test.go

Depends on https://github.com/coreos/mantle/pull/10

Add Cmd interface for extending command execution

---

cmd/kola/qemu.go
network/ssh.go
platform/local/cluster.go
platform/platform.go
platform/qemu.go

Two features for using SSH:
- Access to the full ssh.Session API
- Use the internal SSH agent with external commands
Depends on https://github.com/coreos/mantle/pull/11 and https://github.com/coreos/mantle/pull/10

SSH API improvements

---

cmd/kola/qemu.go
network/ssh.go
platform/local/cluster.go
platform/platform.go
platform/qemu.go

Depends on https://github.com/coreos/mantle/pull/12

platform: support independent cloud configs for each machine

---

cmd/kola/qemu.go
network/ssh.go
platform/local/cluster.go
platform/local/etcd.go
platform/platform.go
platform/qemu.go

Depends on https://github.com/coreos/mantle/pull/13

platform/local: embed stand-alone etcd server

---

cmd/kola/bootchart.go
cmd/kola/kola.go
cmd/kola/qemu.go

Find out what slows down coreos:
```sh
sudo ./kola bootchart --qemu.image=$HOME/latest/coreos_production_image.bin > chart.svg
firefox ./chart.svg
```

Bootchart command for kola

---

platform/local/dnsmasq.go

platform/local: setup loopback interface

---

cmd/kola/etcd.go
cmd/kola/etcdtests/etcdDiscovery.go
cmd/kola/etcdtests/registry.go
platform/local/cluster.go
platform/platform.go
platform/qemu.go

Support for running many etcd tests in kola

---

doc/kola/design.md

kola: add design document

---

cmd/kola/nfs.go

kola: add basic NFS server/client test

---

Godeps/Godeps.json
Godeps/_workspace/src/google.golang.org/api/compute/v1/compute-api.json
Godeps/_workspace/src/google.golang.org/api/compute/v1/compute-gen.go
auth/google.go
cmd/plume/upload.go

This unifies uploading to Google Storage and creating an image in GCE
into one step. The Google Storage filename is mapped into an image name
for simplicity.

cmd/plume: upload cmd also creates GCE image

---

.travis.yml
cmd/kola/bootchart.go
cmd/kola/kola.go
util/exec_test.go

Need to start catching our stupid build errors :-P

Build fixes and enable Travis

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/kylelemons/godebug/diff/diff.go
Godeps/_workspace/src/github.com/kylelemons/godebug/diff/diff_test.go
Godeps/_workspace/src/github.com/kylelemons/godebug/pretty/.gitignore
Godeps/_workspace/src/github.com/kylelemons/godebug/pretty/doc.go
Godeps/_workspace/src/github.com/kylelemons/godebug/pretty/examples_test.go
Godeps/_workspace/src/github.com/kylelemons/godebug/pretty/public.go
Godeps/_workspace/src/github.com/kylelemons/godebug/pretty/public_test.go
Godeps/_workspace/src/github.com/kylelemons/godebug/pretty/reflect.go
Godeps/_workspace/src/github.com/kylelemons/godebug/pretty/reflect_test.go
Godeps/_workspace/src/github.com/kylelemons/godebug/pretty/structure.go
Godeps/_workspace/src/github.com/kylelemons/godebug/pretty/structure_test.go
network/ntp/ntpd/ntpd.go
network/ntp/protocol.go
network/ntp/protocol_test.go
network/ntp/server.go

Started hacking on this over the weekend, not integrated into the local platform code yet but once it is it should help with coretest and enable more comprehensive NTP client testing.

First pass at a NTP implementation

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/coreos/pkg/capnslog/README.md
Godeps/_workspace/src/github.com/coreos/pkg/capnslog/example/hello_dolly.go
Godeps/_workspace/src/github.com/coreos/pkg/capnslog/formatters.go
Godeps/_workspace/src/github.com/coreos/pkg/capnslog/glog_formatter.go
Godeps/_workspace/src/github.com/coreos/pkg/capnslog/log_hijack.go
Godeps/_workspace/src/github.com/coreos/pkg/capnslog/logmap.go
Godeps/_workspace/src/github.com/coreos/pkg/capnslog/pkg_logger.go
Godeps/_workspace/src/github.com/coreos/pkg/capnslog/syslog_formatter.go
cli/cli.go
cmd/kola/kola.go
kola/harness.go

Depends on https://github.com/coreos/pkg/pull/20

Misc updates for mantle/kola

---

kola/tests/coretest/etcd.go

The cluster health function is ripped off from the EtcdDiscovery tests
but modified to run locally instead of remotely. This whole thing needs
to be gutted to not use curl and/or moved out of coretest, there isn't
any reason for it to be local except for its history.
Until then at least it doesn't fail now :)

coretest: wait for the etcd cluster before beginning etcd tests

---

kola/tests/etcd/discovery.go

etcd1 clusters can report healthy with one or two hosts so continue
looping if not enough hosts report as healthy.

kola: check etcd1 cluster health reliably

---

kola/coretest.go
kola/tests/coretest/core.go

this wasn't originally in coretest, but it seemed ok for this test to live here until we reorganize them.
should this test userdel too?

kola/tests/coretest: add useradd test

---

kola/harness.go
platform/platform.go

on my spinning rust,
before: `2015-09-13T01:34:30Z kola: --- PASS: Etcd2Discovery on qemu (41.673s)`
after: `2015-09-13T01:33:10Z kola: --- PASS: Etcd2Discovery on qemu (24.825s)`

parallel NewMachines

---

kola/coretest.go
kola/tests/coretest/core.go

kola: add test for randomized disk UUID

---

kola/etcdregistry.go
kola/tests/etcd/discovery.go
kola/tests/etcd/rolling.go
kola/tests/etcd/util.go

Check health by setting and getting a few keys.

kola/tests/etcd: make etcd1Discovery pass

---

platform/gce.go

When scripting image uploads before a kola run, ongoing image creation
operations would cause kola to fail. This change makes image uploads
wait for the image create operation to complete before returning.

platform/gce: wait for image creation to finish on request

---

kola/tests/etcd/discovery.go

Setting etcd2 to Type=notify means etcd2.service will not finish
starting until the cluster is operational. The cluster will not be
operational until enough etcd nodes have been started. Therefore
blocking until the first node reports as started is a deadlock.
Broke with https://github.com/coreos/coreos-overlay/pull/1576 on Thursday but no one seems to have noticed until I did a release today :( :( :(

etcd/discovery: do not block while starting etcd

---

kola/tests/fleet/fleet.go

Increasing EtcdRequestTimeout to 60+ seconds still causes the start
command to reliably fail. It seems to have no effect. Retrying seems to
work reliably. This is needed to not have this break a jenkins build
every other run.

kola/tests/fleet: need to retry first command to wait for etcd to settle

---

kola/flannelregistry.go
kola/tests/flannel/flannel.go

kola: add flannel smoke test

---

kola/kuberegistry.go
kola/tests/kubernetes/masterconfig.go
kola/tests/kubernetes/multinode.go
kola/tests/kubernetes/nodeconfig.go
platform/platform.go

Starts a 3 node kubernetes cluster using offical kubernetes guides at: http://kubernetes.io/v1.0/docs/getting-started-guides/coreos/coreos_multinode_cluster.html
There are multiple ways of going about setting up a cluster, this i just the first one I choose that worked reasonably well for me. In the future I'd also like a test that sets up a test strictly following our docs and launches the same smoke tests.

kola/tests: add kubernetes smoke test

---

sdk/download.go

See: https://github.com/coreos/mantle/pull/143
@marineam

sdk: retry on download failures

---

cmd/cork/create.go
sdk/create.go

Only taken 3-4 months from starting this branch to finally finishing it. :-P
Next step: run repo inside the chroot to fetch the source tree if it doesn't already exist.

cork: begin support for creating SDK chroots

---

kola/systemdregistry.go
kola/tests/systemd/journald.go

this test will not pass until we fix libmicrohttpd, wrt coreos/bugs#919

kola: add systemd journal gatewayd/remote test

---

cmd/kola/kola.go

See https://github.com/coreos/mantle/issues/183
example output:
```
$ ./bin/kola list
Test Name			Platforms Available
coreos.basic			[all]
coreos.cluster			[all]
coreos.etcd0.discovery		[all]
coreos.etcd2.discovery		[all]
coreos.flannel.udp		[aws gce]
coreos.flannel.vxlan		[aws gce]
coreos.fleet.etcdproxy		[all]
coreos.ignition.sethostname	[aws]
coreos.internet			[gce aws]
coreos.rkt.install		[all]
google.kubernetes.multinodesmoke[gce aws]
linux.nfs.v3			[qemu aws]
linux.nfs.v4			[qemu aws]
linux.ntp			[qemu]
systemd.journal.remote		[all]
```
(output is correctly aligned in terminal output)

cmd/kola: make kola list show available platforms

---

kola/tests/metadata/contents.go

coreos-metadata v0.3.0 renamed the variables.

kola/test/metadata: add support for new names

---

kola/tests/coretest/etcd.go
kola/tests/coretest/testgroupglue.go
kola/tests/etcd/discovery.go
kola/tests/etcd/rolling.go
kola/tests/etcd/util.go

https://github.com/coreos/mantle/issues/131

reinstate etcdctl

---

platform/local/cluster.go

Fixes https://github.com/coreos/mantle/issues/216

platform/local: Clean up NTP server

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/coreos/pkg/capnslog/README.md
Godeps/_workspace/src/github.com/coreos/pkg/capnslog/init_windows.go
Godeps/_workspace/src/github.com/coreos/pkg/capnslog/journald_formatter.go
Godeps/_workspace/src/github.com/coreos/pkg/multierror/multierror.go
platform/local/cluster.go
util/destructor.go

Prevents sillyness like #216 from happening in the future.

Destructor interface and utilities

---

kola/tests/misc/omaha.go
network/omaha/server.go
network/omaha/server_test.go
platform/local/cluster.go
platform/qemu.go

kola/tests/misc: implement coreos.omaha.ping test

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/spf13/pflag/.travis.yml
Godeps/_workspace/src/github.com/spf13/pflag/README.md
Godeps/_workspace/src/github.com/spf13/pflag/bool.go
Godeps/_workspace/src/github.com/spf13/pflag/count.go
Godeps/_workspace/src/github.com/spf13/pflag/duration.go
Godeps/_workspace/src/github.com/spf13/pflag/flag.go
Godeps/_workspace/src/github.com/spf13/pflag/float32.go
Godeps/_workspace/src/github.com/spf13/pflag/float64.go
Godeps/_workspace/src/github.com/spf13/pflag/golangflag.go
Godeps/_workspace/src/github.com/spf13/pflag/int.go
Godeps/_workspace/src/github.com/spf13/pflag/int32.go
Godeps/_workspace/src/github.com/spf13/pflag/int64.go
Godeps/_workspace/src/github.com/spf13/pflag/int8.go
Godeps/_workspace/src/github.com/spf13/pflag/int_slice.go
Godeps/_workspace/src/github.com/spf13/pflag/ip.go
Godeps/_workspace/src/github.com/spf13/pflag/ipmask.go
Godeps/_workspace/src/github.com/spf13/pflag/ipnet.go
Godeps/_workspace/src/github.com/spf13/pflag/string.go
Godeps/_workspace/src/github.com/spf13/pflag/string_slice.go
Godeps/_workspace/src/github.com/spf13/pflag/uint.go
Godeps/_workspace/src/github.com/spf13/pflag/uint16.go
Godeps/_workspace/src/github.com/spf13/pflag/uint32.go
Godeps/_workspace/src/github.com/spf13/pflag/uint64.go
Godeps/_workspace/src/github.com/spf13/pflag/uint8.go
Godeps/_workspace/src/github.com/spf13/pflag/verify/all.sh
Godeps/_workspace/src/github.com/spf13/pflag/verify/gofmt.sh
Godeps/_workspace/src/github.com/spf13/pflag/verify/golint.sh

Adds support for merging flag sets and other handy things.

Godeps: update github.com/spf13/pflag

---

sdk/verify.go

pub   4096R/93D2DCB4 2013-09-06
uid       [ unknown] CoreOS Buildbot (Offical Builds) <buildbot@coreos.com>
sub   4096R/74E7E361 2013-09-06 [expired: 2014-09-06]
sub   4096R/E5676EFC 2014-09-08 [expired: 2015-09-08]
sub   4096R/1CB5FA26 2015-08-31 [expires: 2017-08-30]
sub   4096R/B58844F1 2015-11-20 [expires: 2016-11-19]

sdk: add new image signing sub-key B58844F1

---

index/directory.go

Removes a little bit of the tedious detail from our code.

index: use the new Pages helper instead of iterating ourselves

---

cmd/kola/bootchart.go
cmd/kola/qemu.go
kola/harness.go
kola/tests/kubernetes/coreosbasic.go
platform/aws_test.go

This is needed if the SSH keys need to be added to the config.

*: add cloud-config stub to NewMachine calls

---

storage/index/indexer.go

Depends on https://github.com/coreos/mantle/pull/286 and https://github.com/coreos/mantle/pull/287

storage/index: natural sort links for better version ordering

---

lang/natsort/sort.go
storage/bucket.go
storage/bucket_test.go
storage/index/indexer.go
storage/index/job.go
storage/index/set.go
storage/index/sync.go
storage/index/tree.go
storage/object.go
storage/object_test.go
storage/sync.go

This is the last bit of goo before I drop the plume release command itself!

More storage infrastructure code

---

cmd/kola/options.go
kola/harness.go

initial go at tap.
we should really not filter tests and simply emit SKIP's for them so that the number of tests are consistent...

kola: emit tap results

---

cmd/kola/options.go
kola/harness.go
platform/aws.go
platform/base.go
platform/gce.go
platform/platform.go
platform/qemu.go

This fixes the empty Ignition tests.

kola: upload the generated ssh key to aws

---

kola/tests/misc/auth.go
network/ssh.go
platform/aws.go
platform/base.go
platform/gce.go
platform/platform.go
platform/qemu.go

Ensure that ssh login attempts with invalid credentials are rejected

Add authentication test

---

kola/tests/misc/files.go
kola/tests/misc/network.go
kola/tests/misc/users.go

Verify that we don't have any unexpectedly world-writable dirs or
files, no unexpected SUID or SGID files and no unauthorised
network listeners.

Add some additional tests

---

system/anonfile_linux.go
system/anonfile_linux_test.go

After actually starting to use this I changed my mind from what I originally wrote back in December.

Rework AnonymousFile, add PrivateFile

---

cmd/kola/bootchart.go
cmd/kola/qemu.go
cmd/kola/spawn.go
cmd/kola/updatepayload.go
kola/harness.go
kola/tests/misc/omaha.go
platform/machine/qemu/cluster.go
platform/machine/qemu/machine.go

move qemu cluster code to platform/machine/qemu

---

kola/tests/kubernetes/controllerInstall.go
kola/tests/kubernetes/setup.go
kola/tests/kubernetes/workerInstall.go

https://github.com/coreos/coreos-kubernetes/pull/642
@mischief

fix dockernetes breakage in v1151.0.0

---

cmd/kola/updatepayload.go
network/omaha/trivial_server.go
network/omaha/trivial_server_test.go
platform/local/cluster.go

Move trivial update server into network/omaha

---

platform/platform.go

This makes it practical to actually find out why a unit failed.

platform: optionally dump machine log when a unit fails

---

cmd/kola/updatepayload.go
network/omaha/trivial_server.go

Tested with every CoreOS stable branch released so far. Extends the test to check that the upgraded system itself can perform a second upgrade.

Support upgrading from all CoreOS versions

---

cmd/plume/prerelease.go
cmd/plume/specs.go
platform/api/azure/image.go
platform/api/azure/storage.go
platform/api/azure/storage_mit.go
util/bunzip.go

for now, runs stuff for azure. in the future it could do the aws stuff too.

plume pre-release

---

kola/tests/locksmith/locksmith.go

Using coreos-cloudinit to configure and start locksmith properly
exercises the codepath that is encountered in the field. I have no idea
why this test was originally implemented this way, but this new
implementation is more inline with what is actually done.
This now catches https://github.com/coreos/bugs/issues/1562 and https://github.com/coreos/bugs/issues/1588.

kola/tests/locksmith: properly test locksmith

---

cmd/kola/spawn.go
kola/tests/docker/docker.go

Proposes
- Some minor changes to kola spawn, to make it easier to develop and prove out cluster tests
- A new test, that ensures that docker containers can receive and create connections to remote hosts
Bits worth thinking about:
- The kola spawn changes might run counter to decisions made in https://github.com/coreos/mantle/pull/349 
- The timeouts in the docker test are kinda hacky

ensure docker containers can make network connections outside of their hosts

---

sdk/enter.go

gsutil changes the global process umask when writing out
~/.gsutil/credstore but gsutil is multi-threaded so this may conflict
with the automatic creation of the ~/.gsutil/tracker-files directory.
Side step the whole mess by replacing ~/.gsutil with a path under /run
that already contains the tracker-files directory.

sdk: work around gsutil umask bug

---

cmd/cork/create.go

In follow up to https://github.com/coreos/coreos-overlay/pull/2212.
@marineam  There are a lot of ways to do this.  Let me know if you have some preference.

cmd/cork: Add setup command

---

system/exec/exec.go
system/exec/exec_test.go

The previous Kill implementation sent the signal even if the command had
already exited. The new cancel mechanism handles this case properly.

system/exec: add CommandContext from go1.7 and reimplement Kill

---

kola/tests/misc/files.go

This shouldn't be recursing into the rkt containers.

kola/tests: fix writabledirs test

---

Godeps/Godeps.json
cli/cli.go
vendor/github.com/coreos/pkg/capnslog/logmap.go

Been a TODO ever since migrating to cobra+pflag

Fix --log-level cli option

---

kola/tests/docker/docker.go

UPDATED: Running the new test now depends on (ONLY) https://github.com/coreos/coreos-overlay/pull/2257 - this can also merge before that, since the new test is skipped unless the old client is available.

Old docker client test

---

Jenkinsfile

This will allow other various plugins/steps to work with the generated files in the workspace directory.

Jenkinsfile: run in Docker with the same UID/GID

---

Jenkinsfile

jenkins: Only archive master artifacts

---

cmd/kola/updatepayload.go
platform/machine/aws/machine.go
platform/machine/gcloud/machine.go
platform/machine/qemu/machine.go
platform/platform.go

Needed to support custom Reboot behavior in different machine types.

platform: add Reboot to Machine interface

---

Godeps/Godeps.json
cmd/kola/updatepayload.go
network/journal/_test/main.go
network/journal/format.go
network/journal/format_test.go
network/journal/record.go
network/journal/record_test.go
platform/journal.go
platform/machine/qemu/cluster.go
platform/machine/qemu/machine.go
platform/util.go
vendor/github.com/kballard/go-shellquote/LICENSE
vendor/github.com/kballard/go-shellquote/README
vendor/github.com/kballard/go-shellquote/doc.go
vendor/github.com/kballard/go-shellquote/quote.go
vendor/github.com/kballard/go-shellquote/unquote.go

When using the qemu platform in kola each machine's journal is logged to:
_kola_temp/$testname/$machineid/journal.txt

Record journal for qemu machines

---

platform/machine/aws/cluster.go
platform/machine/aws/machine.go
platform/util.go

Removes old Reboot function now that it is unused.

platform: add output dir support for AWS

---

cmd/kola/updatepayload.go
kola/tests/coretest/testgroupglue.go
kola/tests/etcd/discovery.go
kola/tests/etcd/rolling.go
platform/platform.go
platform/util.go

This has been replaced by the new and improved journal mechanism.

platform: remove StreamJournal and its users

---

harness/sub_test.go
harness/testing.go

Starting to consolidate global state into Suite

Harness refactoring

---

kola/tests/docker/docker.go

This Docker test has never passed.  This fixes it.

kola/tests/docker: define network test userdata

---

kola/tests/misc/files.go

This is a follow-up to coreos/bugs#1807.  It checks `/` and `/usr`.  It might be worth extending to some of the tmpfs file systems to verify all tmpfiles.d settings, but then more whitelists would need to be added since there are packages intentionally creating broken links.

kola/tests/misc: add a test to find broken symbolic links

---

kola/tests/docker/docker.go

Tested locally against the current stable ami and verified it passed (specifically: `AWS_REGION=us-west-2 ./bin/kola run --platform aws  --aws-ami ami-444dcd24 --aws-type t2.small --basename "euank-kola-test" "docker.user-no*"`)

kola/docker: add regression test for CVE-2016-8867

---

Jenkinsfile
cmd/cork/create.go
cmd/cork/download.go
cmd/cork/downloadimage.go
cmd/kola/options.go
cmd/plume/prerelease.go
platform/machine/qemu/cluster.go
sdk/download.go
sdk/enter.go
sdk/verify.go
sdk/verify_test.go
test

Some enhancements.
With the patch `Jenkinsfile: Restrict to sdk node` you will need to add the `sdk` label to your jenkins nodes.

enhancements

---

harness/doc.go
harness/harness_test.go
harness/suite.go
harness/test.go
harness/test_test.go
kola/harness.go

Replaces the old InternalTest type

harness: add new Tests type for managing a set of tests

---

kola/tests/misc/files.go

If we move any directory onto a tmpfs and forget to set its permissions, it'll end up mode 1777, and `coreos.filesystem.writabledirs` ignores sticky directories.

kola/tests/misc: check for non-whitelisted sticky directories

---

pluton/tests/bootkube/destructiontests.go
pluton/tests/bootkube/registry.go

cc @hongchaodeng This is for testing https://github.com/kubernetes-incubator/bootkube/pull/380

pluton: self-hosted etcd destruction tests

---

pluton/tests/bootkube/registry.go
pluton/tests/bootkube/scale.go

While we are here, tweak error handling a little.
cc @marineam

pluton/tests/bootkube: scale test is too flakey for main test namespace

---

pluton/tests/bootkube/registry.go
pluton/tests/bootkube/scale.go

pluton: move self-hosted destructive tests into main CI

---

kola/tests/misc/verity.go

Not actually tested on arm64, since both the SDK and system versions of qemu-system-aarch64 on my machine spin in a tight loop without doing anything.

kola/tests/misc: use correct verity hash offset on arm64-usr

---

pluton/tests/bootkube/registry.go
pluton/tests/bootkube/scale.go

pluton/bootkube/tests: re-enable scale test

---

cmd/pluton/options.go
cmd/pluton/pluton.go
pluton/spawn/nodeconfig.go
pluton/tests/bootkube/conformance.go
pluton/tests/bootkube/registry.go
pluton/upstream/conformance.go

While we are here bump some default versions.

pluton: enable self-hosted conformance

---

harness/harness.go
harness/harness_test.go

Tests can now use H.TempDir and H.TempFile to toss temporary data into
the output directory which can be inspected later after test execution.
H.OutputDir is also available so customized test suites can output
data using predetermined names as well. Individual tests should stick
with the randomized names created by Temp* to avoid conflicts.

harness: add support for test data under the output directory

---

cmd/kola/options.go
cmd/ore/ore.go
cmd/pluton/options.go
platform/api/gcloud/api.go

This should allow us to drop our GCE worker in Jenkins.

cli: support GCE service account JSON key authentication

---

kola/tests/misc/ntp.go
kola/tests/misc/omaha.go

NTP wasn't actually returning an error on failure, and Omaha was dropping into a manhole on failure.

Misc test fixes

---

platform/api/aws/s3.go

Introduced in the previous commit.
I sure do love software.

platform/aws: fix 404 check error

---

cmd/kola/kola.go
kola/harness.go
kola/register/register.go
kola/tests/docker/docker.go

Fixes https://github.com/coreos/mantle/issues/423

Support filtering kola tests by machine architecture

---

cmd/ore/aws/upload.go
cmd/plume/prerelease.go
cmd/plume/release.go
cmd/plume/specs.go
platform/api/aws/images.go
platform/api/aws/s3.go

Addresses #2, #106, coreos/bugs#1900.

plume: Support AWS

---

cmd/pluton/options.go

might help with s3 being wonky while a better solution is worked on. @marineam

cmd/pluton: change default region to be a little closer to s3

---

cmd/plume/prerelease.go
platform/api/aws/images.go

couple small bugs I ran into
cc @bgilbert

aws: govcloud tweaks

---

pluton/tests/bootkube/destructiontests.go

cc @pbx0 @squat
Ref https://github.com/kubernetes-incubator/bootkube/pull/422

pluton/tests/bootkube: Update API server delete test with the new labels.

---

pluton/spawn/bootkube.go

These changes are needed to make the tests pass after this bootkube
change:
https://github.com/kubernetes-incubator/bootkube/pull/425
We should only merge these changes in conjunction with that one.

Quick and dirty flag fixes to match bootkube changes.

---

Jenkinsfile

This is the Jenkins side of coreos/coreos-overlay#2522.

Jenkinsfile: build with go1.8

---

pluton/spawn/bootkube.go

Flag changes for https://github.com/kubernetes-incubator/bootkube/pull/437

Flag changes to match bootkube change

---

cmd/pluton/options.go
pluton/harness/options.go
pluton/harness/run.go
pluton/spawn/bootkube.go
pluton/spawn/nodeconfig.go

WIP since I'm still debugging locally on why this doesn't work.
cc @diegs

pluton: use init-master.sh script from bootkube repo directly

---

cmd/kola/updatepayload.go
network/neterror/error.go
network/ntp/server.go
network/omaha/handler.go
network/omaha/server.go
network/omaha/trivial_server.go
network/omaha/trivial_server_test.go

Some improvements so I can use my omaha server for unit tests in the Tectonic Channel Operator.

Improve omaha package for use by external projects

---

pluton/tests/bootkube/scale.go

Etcd scale test was broken for more then one reason. This fixes the test
itself breaking when the insecure api-server port was disabled by using
authorized kubectl commands to edit the spec now that we can do that
post 1.6
cc @hongchaodeng

pluton/tests: fix etcd-scale test

---

platform/api/aws/api.go

I'm not certain of the reason, but the previous implementation didn't
work. I tried it with a different partition/profile, and I suspect it
ignored the profile. After this change, an identical command worked.

platform/aws: fix handling of credential file

---

pluton/spawn/bootkube.go
pluton/tests/bootkube/registry.go

pluton: re-enable tests

---

platform/api/aws/ec2.go
platform/machine/aws/cluster.go
platform/machine/aws/machine.go

- Double the launch timeout so we don't give up on PV instances prematurely
- Notice launch failures before the timeout
- Fix instance leaks on CreateInstances() failure
- Set the Name tag when creating instances

kola: AWS improvements

---

cmd/kola/spawn.go

Don't `os.Exit(1)` with pending deferred cleanups.

cmd/kola: Fix "kola spawn" instance leak if shell exits nonzero

---

cmd/plume/prerelease.go
cmd/plume/release.go
cmd/plume/specs.go
platform/api/aws/images.go

This code was just used to release Alpha.

cmd/plume: Some Azure improvements

---

platform/api/aws/ec2.go

platform/aws: create security groups if they don't exist

---

pluton/tests/bootkube/destructiontests.go

for https://github.com/kubernetes-incubator/bootkube/pull/492

pluton/tests/bootkube: update apiserver label

---

pluton/spawn/bootkube.go

Bumps etcd-operator to v0.2.6.

Bump pluton etcd-operator precache version.

---

kola/tests/docker/docker.go

This is related to the 'docker-skim' work where I wish to just call
'dockerMetaTests' on skim rather than throw the full suite at it since
duplicating the full suite has been a bit messy.
This also should speed things up a little.
Threw it at AWS once by hand and things looked fine.
cc @bgilbert

kola/tests/docker: use subtests for simple tests

---

.travis.yml

use go 1.8 with travis ci

---

cmd/plume/prerelease.go

No platform has pre-release dependencies on any other, so allow selecting a subset of platforms to pre-release. This is intended to support pre-releasing platforms separately in Jenkins. Similar functionality is not extended to `plume release` because (a) `release` is supposed to be relatively fast, and (b) we don't want to risk performing a partial release. `plume release` will catch missing artifacts on each platform, so a partial pre-release won't slip by undetected.
cc: @dm0

cmd/plume: Allow pre-releasing each platform independently

---

kola/harness.go

kola: Skip cluster semver check unless some test needs it

---

kola/tests/misc/network.go

The lsof checker in use before had occational false positives on UDP
since it was unable to distinguish listening from requesting.
Specifically, timesyncd appeared a couple times even though it was only
making a DNS request.
This switches to netstat which, as best I can tell, has better filtering
for 'listening and udp'.
This also changes ports to be numeric simply because I find that easier
to read.
Functionally, this should be the same as before.
This should fix the flake we saw last nightly build.
I tested that deleting some of the expected items does fail the test.
cc @bgilbert since we talked about this briefly.

kola/tests/network-listener: check for listeners with netstat

---

platform/machine/qemu/cluster.go

Use the base image as COW backing store for a qcow2 disk image. This saves 750 MB of I/O per instance, avoids thrashing the page cache, and reduces SSD wear. On my SSD-backed system, starting from a cold cache, it reduces the `kola run` runtime from 840s to 595s.

qemu: Avoid copying disk image

---

platform/machine/qemu/disk.go

Hopefully fixes intermittent `mount(8)` failures in Jenkins.

platform/machine/qemu: Wait for OEM block device before mounting it

---

kola/tests/fleet/fleet.go

The fleet documentation claims that starting units should block until it's active, but that is not the case.  Since fleet is slated for removal from the OS in February 2018, just add back retry logic that was there originally so tests aren't randomly failing.

kola/tests/fleet: Retry unit status detection

---

cmd/plume/prerelease.go

Avoid requiring Jenkins to download AMI ID files in order to test the uploaded images.

cmd/plume: Have pre-release write image IDs to optional output file

---

platform/api/aws/images.go

This will turn it into an error which, in theory, could be retried by
publish eventually.
For now it's still fatal, but this is still nicer.
cc @bgilbert

api/aws: remove a possible panic in publish

---

kola/tests/ignition/root.go

The current test validates `mkfs.ext4 -p`, but we no longer carry the e2fsprogs patch for that option. Ignition now detects existing filesystems itself via blkid, and that functionality should be tested by its test suite, but it's still useful to have one integration test here.
Testing the non-force case with pre-2.1 configs would produce a boot failure, which is difficult to check. Use `wipeFilesystem=false` and a 2.1 config to test that Ignition doesn't reformat a filesystem with the correct label.

kola/tests/ignition: update ext4checkexisting for current Ignition

---

kola/tests/torcx/torcx.go

Comment I missed on the previous PR..

kola/tests/torcx: name test more clearly

---

kola/tests/misc/raid.go

This commit adds a test wherein the root filesystem is on a software
raid device, and tests whether the machine can survive a reboot and come
up successfully.

kola/tests/misc: add test for root fs on a raid device

---

kola/tests/docker/docker.go

Add test to kill containerd and ensure it restarts. Refactor docker info
logic to be common between docker info test and this test.
Depends on: https://github.com/coreos/coreos-overlay/pull/2703

kola/tests: add test for restarting containerd

---

kola/tests/misc/raid.go

Adds a test that raids together the OEM-CONFIG and USR-B partitions and mounts them at `/var/lib/data`. This test does not test if the raid array still functions after a reboot, therefore `/usr/share/oem/grub.cfg` doesn't need to be overwritten and it should be able to run on all platforms.

kola/test/misc/raid.go: add coreos.disk.raid.data

---

cmd/kola/kola.go

cmd/kola: Document special handling of single test name by kola run

---

README.md

Do no merge, still working on it

readme: update to be accurate

---

kola/registry/registry.go
kola/tests/packages/ipvsadm.go
kola/tests/packages/packages.go

For https://github.com/coreos/coreos-overlay/pull/2707

kola/tests: add test that ipvsadm works

---

kola/tests/misc/files.go

https://github.com/coreos/coreos-overlay/pull/2734

kola/tests/misc: Update comment

---

sdk/download.go

This should fix most build failures caused by GCS, since bad HTTP responses seem to be random incidents.

sdk: Retry GCS API failures same as downloads

---

kola/tests/misc/raid.go

Use new gpt partition type uuids from https://github.com/coreos/bootengine/pull/132
Depends on https://github.com/coreos/mantle/pull/689

 kola/tests: update root on raid to use uuids

---

kola/tests/locksmith/locksmith.go

Adds a test that ensures that locksmith can successfully reboot without
etcd in the default configuration.
Passes with https://github.com/coreos/locksmith/pull/130

kola: add coreos.locksmith.reboot test

---

platform/machine/qemu/disk.go

It's more direct than kpartx and requires one fewer dependency.

platform/machine/qemu: use loop device partitions for kola mkimage

---

kola/harness.go

Avoid races when multiple kola runs are started in close succession.
cc @ajeddeloh

kola: atomically update _kola_temp platform-latest symlink

---

.travis.yml
Jenkinsfile

Replaces #714 
I'd like to use a shiny new go 1.9 feature, this seems like a good first step.

Update to go 1.9

---

cmd/kola/options.go

Add option to use different AWS profiles.

cmd/kola: add profile option

---

kola/tests/misc/nfs.go

`linux.nfs.v3` & `linux.nfs.v4` use cloudconfig. This ports them
to Container Linux Configs.

kola/tests: rewrite linux.nfs.* to use CLC

---

kola/cluster/cluster.go
kola/tests/docker/docker.go
kola/tests/docker/torcx_docker_flag.go
kola/tests/docker/torcx_manifest_pkgs.go
kola/tests/ignition/execution.go
kola/tests/ignition/filesystem.go
kola/tests/ignition/sethostname.go
kola/tests/kubernetes/kubelet_wrapper.go
kola/tests/kubernetes/setup.go
kola/tests/locksmith/locksmith.go
kola/tests/metadata/contents.go
kola/tests/misc/files.go
kola/tests/misc/network.go
kola/tests/misc/nfs.go
kola/tests/misc/ntp.go
kola/tests/misc/omaha.go
kola/tests/misc/raid.go
kola/tests/misc/selinux.go
kola/tests/misc/toolbox.go
kola/tests/misc/update.go
kola/tests/misc/users.go
kola/tests/misc/verity.go
kola/tests/packages/ipvsadm.go
kola/tests/rkt/rkt.go
kola/tests/systemd/journald.go
kola/tests/systemd/sysusers.go
kola/tests/torcx/torcx.go

Drop a bunch of boilerplate error checking.

kola: Add c.MustSSH()

---

cmd/ore/gcloud/delete-images.go

cmd/ore/gcloud: add delete-images subcommand

---

.travis.yml
Jenkinsfile

Part of coreos/coreos-overlay#2914

*: Bump Go to 1.9.2 to stay in sync with the overlay

---

kola/tests/ignition/resource.go

Adds a new test targeting a remote S3 config which is not viewable
anonymously. It has read access granted to the AuthenticatedUsers
AWS group (similar to the other S3 resource tests).

kola/tests: add test for remote s3 config

---

platform/machine/qemu/machine.go

Clean up the error handling and actually log the errors when they occur.
I chose to log the error inside `Destroy()` instead of at the caller because `Destroy()` is frequently called in as `defer m.Destroy()` or in cleanup when creating a cluster fails. Furthermore there's usually not any action we'd take when `Destroy()` fails other than logging it.
I'll see what feedback there is for this, then port it to the other platforms once this is hammered out.
This will hopefully provide at least a start to figuring out what's going on with https://github.com/coreos/mantle/issues/768

platform/qemu: clean up error handling

---

platform/journal.go

Go's gzip package does not close the underlying io.Writer. Make a
wrapper struct to keep track of the original and close both when Close()
is called on it.

platform/journal: fix leaked file handle

---

platform/api/do/api.go
platform/machine/do/cluster.go

The api package wraps the error from DO so the shouldRetry logic doesn't
detect the DO errors correctly. Move the logic to the api package so it
can correctly detect the error type.

platform/do: move retry logic to platform

---

kola/tests/docker/docker.go
kola/tests/docker/torcx_docker_flag.go
kola/tests/docker/torcx_manifest_pkgs.go
kola/tests/etcd/discovery.go
kola/tests/ignition/filesystem.go
kola/tests/misc/network.go
kola/tests/misc/nfs.go
kola/tests/misc/raid.go
kola/tests/packages/packages.go
kola/tests/torcx/torcx.go

They cause unnecessary semver checks.

kola/tests: drop old MinVersions

---

sdk/enter.go

bind mount ~/.gnupg to the same directory in the sdk. Mounting it other
places causes gpg to ignore the /run/user/$uid/gnupg directory and
create temp directories instead, although it is unclear why.
Always mount the /run/user/$uid/gnupg directory to the same location in
the sdk becuase configuring gpg to use a different directory is no
longer as simple as using the GPG_AGENT_INFO environment variable.
Addresses https://github.com/coreos/mantle/issues/622

cork: pass through gpg sockets

---

platform/api/aws/ec2.go
platform/machine/aws/machine.go

platform/machine/aws: try harder to get complete console logs

---

cmd/ore/do/delete-keys.go
cmd/ore/do/list-keys.go
platform/api/do/api.go

cmd/ore/do: add list-keys and delete-keys commands

---

kola/tests/misc/grub.go

Add tests for binary patching grub's linux.mod.

kola/tests: add binpatching test

---

glide.lock
glide.yaml
vendor/github.com/digitalocean/godo/domains.go
vendor/github.com/digitalocean/godo/godo.go
vendor/github.com/digitalocean/godo/storage.go

This should fix problems with handling non-json errors.

vendor: update godo to 1.1.3

---

cmd/kola/spawn.go

This introduces a new `--omaha-package` flag to `kola spawn`, in order
to add an update payload to the omaha server and point spawned node to
it.

kola/spawn: add omaha-package support

---

cmd/cork/create.go
sdk/enter.go

depends on https://github.com/coreos/scripts/pull/820

cork: drop deprecated enter method

---

cmd/ore/aws/upload.go

Signed-off-by: Sayan Chowdhury <sayan.chowdhury2012@gmail.com>

[WIP] ore: Add functionality to add custom tags to AMIs

---

kola/tests/misc/network.go

This test has been failing a lot lately.  I'll run this through Jenkins to see if it helps.

kola/tests: Retry the network listeners test

---

sdk/enter.go

sdk/enter: add trailing newline to resolv.conf

---

cmd/cork/create.go
sdk/repo.go

This was already added to enter, but update/create was omitted. Add
those.

cmd/cork: add --use-host-dns to update/create

---

kola/tests/misc/nfs.go

Updates the NFS test to no longer write to use /var/mnt rather than
/mnt, adds the ability to specify what is being mounted, and adds a
RHCOS specific NFSv4 test.

kola/tests/misc/nfs: add RHCOS specific NFS test

---

platform/api/aws/images.go

`CopyImage`, like `PublishImage` before 2c86de6fe4f5, assumes that the first `BlockDeviceMapping` is the EBS snapshot.  That is not necessarily true.
Untested.

platform/api/aws: handle out-of-order BDMs in CopyImage

---

platform/api/aws/ec2.go

Ignores `InvalidInstanceID.NotFound` errors during machine creation. This
most commonly happens when AWS itself is having issues.

platform/api/aws/ec2: reduce machine creation flakes

---

kola/tests/ignition/passwd.go

The current ignition user tests were failing on RHCOS because RHCOS
does not have a docker group by default like CL.  There was a
subsequent failure due to the UID difference for the core user and
creation of new users.
The original tests were modified to only run on CL.  New tests were
added for RHCOS to account for no docker group and UID difference.

kola/tests/ignition: adapt for RHCOS

---

kola/tests/crio/crio.go

Podman builds seem to have changed default tag prefix, fixing and changed tagging to prevent similar errors in the future.

Fix image name in container config

---

README.md
kola/tests/coretest/core.go
kola/tests/etcd/discovery.go
kola/tests/flannel/flannel.go
kola/tests/ignition/empty.go
kola/tests/ignition/execution.go
kola/tests/ignition/filesystem.go
kola/tests/ignition/passwd.go
kola/tests/ignition/sethostname.go
kola/tests/locksmith/locksmith.go
kola/tests/metadata/contents.go
kola/tests/misc/cloudinit.go
kola/tests/misc/files.go
kola/tests/misc/grub.go
kola/tests/misc/install.go
kola/tests/misc/network.go
kola/tests/misc/omaha.go
kola/tests/misc/raid.go
kola/tests/misc/tls.go
kola/tests/misc/toolbox.go
kola/tests/misc/update.go
kola/tests/misc/users.go
kola/tests/misc/verity.go
kola/tests/rkt/rkt.go
kola/tests/update/update.go

Implements a new test namespacing policy and updates existing tests to
follow it.

kola/tests: change test namespacing policy

---

kola/tests/misc/nfs.go

Part of coreos/coreos-overlay#3348

kola/tests/misc: Switch CL to the RHCOS NFS test

---

kola/tests/podman/podman.go

Use the FailFast functionality introduced in #926 for the podman
workflow test so test reporting is clearer and dependent tests are
skipped when a failure occurs.
Also fixed some minor variable casing caught by golint.

kola/tests: use FailFast for podman workflow test

---

cmd/kola/options.go
kola/harness.go
kola/tests/coretest/core.go
kola/tests/ignition/execution.go
kola/tests/ignition/passwd.go
kola/tests/ignition/resource.go
kola/tests/ignition/security.go
kola/tests/ignition/sethostname.go
kola/tests/misc/auth.go
kola/tests/misc/nfs.go
kola/tests/misc/selinux.go
kola/tests/rpmostree/deployments.go
kola/tests/rpmostree/status.go
kola/tests/systemd/sysusers.go
platform/platform.go

Note: The test related changes are only for tests that run on the `qemu` platform.

*: add fcos distribution

---

.travis.yml
Jenkinsfile
cmd/kola/kola.go

gofmt 1.11 has different opinions than 1.10 about `kola.go`.

Update CI to Go 1.11

---

platform/api/azure/replication.go

Attempt to filter out locations which will fail image replication because they are still being bootstrapped.

platform/api/azure: don't list locations without Compute service

---

kola/tests/ignition/resource.go

Adds a test for pulling versioned s3 objects (a new feature in
Ignition).
Tests both a null versionId (AWS uses this for the original version of a
file) and a later versionId.
Closes #933

kola/tests/ignition: add test for versioned s3 objects

---

cmd/kola/kola.go
cmd/kola/options.go

Adds distribution information to the list subcommand. Also adds a new
flag `--json` to the list subcommand.

cmd/kola: list improvements

---

kola/tests/misc/selinux.go

Previously, the SELinux boolean tests assumed a default value for the
boolean that was being tested.  When RHCOS flipped this value during
its compose, the tests broke.
This changes the tests to query the boolean first, then flip the value
of it during the test.
This introduces `toggleSelinuxBoolean()`, which accepts a SELinux
boolean to query and returns an array with the flipped values to be
used later.

kola/tests/misc/selinux: refactor SELinux boolean tests

---

kola/tests/podman/podman.go

Podman has some minor formatting changes in its command output:
- displays only 12 characters of container IDs
- id/image/status changed to ID/Image/Status
- more detailed statuses
This commit accounts for these changes and relaxes the check on the
status.

kola/tests/podman: update output validation

---

kola/tests/ostree/basic.go

A fresh image has 0 or more remotes. Get the initial list and use that in tests.

WIP: kola/tests: Sense initial remotes before running ostree remotes tests

---

kola/tests/rpmostree/deployments.go

Move away from `fpaste` as the package to test with because it
requires Python2 on the host and that is not available in RHCOS.
I made the name of the package and the path to the binary variables
for easier reuse.  I also dropped the check on running the binary.
The tests pass the latest RHCOS and should pass FCOS, but I was
unable to run `kola` against FCOS.

kola/tests/rpmostree: use different pkg for 'rpm-ostree (un)install'

---

README.md
kola/README.md

Split off from https://github.com/coreos/coreos-assembler/pull/518

[kola/]README.md: Quick start addition for test writing

---

MAINTAINERS

I can't give mantle the time it deserves.  @ajeddeloh and @jlebon have agreed to help with reviewing.  (And other reviewers are always welcome!)

MAINTAINERS: drop bgilbert

---

platform/qemu.go

Disable auto-read-only. A patch was added in qemu[1] `v3.1.0-rc0` & `v4.0.0`
that returns `-EACCESS` if the node is read-write and `BDRV_O_AUTO_RD_ONLY`
is not set or `bdrv_can_set_read_only()` forbids making the node
read-only.
[1] https://github.com/qemu/qemu/commit/eaa2410f1ea864609090c0a5fda9e0ce9499da79

platform/qemu: disable auto-read-only on qemu disks

---

kola/tests/coretest/core.go

In RHCOS, we are explicitly disabling certain services.  These
additional tests will verify that we don't regress.

kola/tests/coretest/core: add RHCOS checks for disabled services

---

cmd/plume/release.go

Use an empty json instead of failing when there is no releases.json

plume: handle non-existent fcos releases.json

---

cmd/ore/aws/upload.go
platform/api/aws/images.go

This matches the semantic intended for coreos-assembler.
Closes: https://github.com/coreos/mantle/issues/1035

ore: Make upload --force deregister AMI too

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/feature.md

Adds a feature template per meeting.
/cc @darkmuggle @ajeddeloh @lucab @vrutkovs @arithx

Add feature template

---

platform/api/aws/images.go

The `createImage` call currently can fail when attempting to tag the AMI
Name due to eventual consistency issues. Add a `RetryConditional` to
retry up to 6 times when `InvalidAMIID.NotFound` is returned by the SDK.
Closes #1030
Closes #1091

platform/api/aws/images: retry tagging image name

---

platform/api/aliyun/api.go

Add a ListRegions API call similar to AWS for use in COSA.

platform/api/aliyun: add ListRegions API call

---

kola/registry/registry.go
kola/tests/fips/fips.go

FIPS is available on RHCOS now so lets add a test for it.

kola: add basic fips test

---

platform/qemu.go

With the changes made recently: https://github.com/coreos/coreos-assembler/pull/826, we need to add
support for detecting LUKS root partitions which is really unnecessary as we are just injecting ignition
in the boot partition.
Based on suggestions by @cgwalters and @tuan-hoang1 in #1118

Do not mount root parition for injecting ignition

---

cmd/kola/kola.go
cmd/kola/options.go
platform/machine/qemu/cluster.go
platform/machine/qemu/flight.go
platform/machine/unprivqemu/cluster.go
platform/machine/unprivqemu/flight.go
platform/qemu.go

Prep for further work in qemu.

platform/qemu: Drop some CL disk customization bits

---

platform/qemu.go

I'm working on creating a more direct `QemuInstance` struct
so we can use it for a `cosa run` backend separate from the flight
stuff.  This is prep cleanup for it - extract the basics to
a separate helper, and clarify the memory bits in particular.

qemu: Clean up argv handling a bit

---

platform/qemu.go

We can assume we have a modern qemu now since we're running
in coreos-assembler.

qemu: Remove checks for old qemu versions

---

cmd/kola/kola.go

For a while `python3 -m http.server` has been my go-to for
a quick static webserver but it's pretty suboptimal since it's
single-threaded etc. and apparently OSTree's heavy use of
concurrent requests breaks it.
See
https://gist.github.com/cgwalters/4e5eb36bd439f5995928e9232d865f67
Let's add a convenience command here for cases like serving
up a local ostree repo and other things.

kola: Add http-server subcommand

---

platform/machine/unprivqemu/cluster.go
platform/qemu.go

Just a drive-by cleanup, not a dependency of anything.

qemu: Make SSHAddress a method on QemuInstance

---

cmd/kola/options.go
platform/machine/unprivqemu/cluster.go
platform/machine/unprivqemu/flight.go
platform/qemu.go

More moving of code into mantle that was in coreos-assembler.
We want to test UEFI and Secure Boot for obvious reasons.

qemu: Add --qemu-firmware bios|uefi|uefi-secure

---

cmd/plume/prerelease.go
cmd/plume/release.go

Missed those in the first round (#1151).

plume: drop more CL-specific bits

---

cosa/build.go

See individual commit messages.

cosa/build: fix AMIs spec and add a few more fields

---

cmd/kola/qemuexec.go

Plumb through the rest of the bits the CLI needs to support
replacing the guts of `cosa run`.

qemuexec: Add --ignition arg, propagate kola --qemu-* args

---

cmd/kola/kola.go

Intending to replace `coreos-assembler/src/incomplete-hack-ign-3to2`.

kola: Add ign-convert2
